// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Astra
{
    public static class GetAvailableRegions
    {
        /// <summary>
        /// Retrieve a list of available cloud regions in Astra
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using Pulumi;
        /// using Astra = Pulumi.Astra;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var regions = Astra.GetAvailableRegions.Invoke();
        /// 
        /// });
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetAvailableRegionsResult> InvokeAsync(InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetAvailableRegionsResult>("astra:index/getAvailableRegions:getAvailableRegions", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetAvailableRegionsResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The list of supported Astra regions by cloud provider and tier.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetAvailableRegionsResultResult> Results;

        [OutputConstructor]
        private GetAvailableRegionsResult(
            string id,

            ImmutableArray<Outputs.GetAvailableRegionsResultResult> results)
        {
            Id = id;
            Results = results;
        }
    }
}
