// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Astra
{
    public static class GetAccessList
    {
        /// <summary>
        /// `astra.AccessList` provides a datasource that lists the access lists for an Astra database.
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using Pulumi;
        /// using Astra = Pulumi.Astra;
        /// 
        /// class MyStack : Stack
        /// {
        ///     public MyStack()
        ///     {
        ///         var dev = Output.Create(Astra.GetAccessList.InvokeAsync(new Astra.GetAccessListArgs
        ///         {
        ///             DatabaseId = "8d356587-73b3-430a-9c0e-d780332e2afb",
        ///         }));
        ///     }
        /// 
        /// }
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetAccessListResult> InvokeAsync(GetAccessListArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetAccessListResult>("astra:index/getAccessList:getAccessList", args ?? new GetAccessListArgs(), options.WithDefaults());

        /// <summary>
        /// `astra.AccessList` provides a datasource that lists the access lists for an Astra database.
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using Pulumi;
        /// using Astra = Pulumi.Astra;
        /// 
        /// class MyStack : Stack
        /// {
        ///     public MyStack()
        ///     {
        ///         var dev = Output.Create(Astra.GetAccessList.InvokeAsync(new Astra.GetAccessListArgs
        ///         {
        ///             DatabaseId = "8d356587-73b3-430a-9c0e-d780332e2afb",
        ///         }));
        ///     }
        /// 
        /// }
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Output<GetAccessListResult> Invoke(GetAccessListInvokeArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetAccessListResult>("astra:index/getAccessList:getAccessList", args ?? new GetAccessListInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetAccessListArgs : Pulumi.InvokeArgs
    {
        [Input("databaseId", required: true)]
        public string DatabaseId { get; set; } = null!;

        public GetAccessListArgs()
        {
        }
    }

    public sealed class GetAccessListInvokeArgs : Pulumi.InvokeArgs
    {
        [Input("databaseId", required: true)]
        public Input<string> DatabaseId { get; set; } = null!;

        public GetAccessListInvokeArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetAccessListResult
    {
        public readonly ImmutableArray<Outputs.GetAccessListAddressResult> Addresses;
        public readonly string DatabaseId;
        public readonly bool Enabled;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;

        [OutputConstructor]
        private GetAccessListResult(
            ImmutableArray<Outputs.GetAccessListAddressResult> addresses,

            string databaseId,

            bool enabled,

            string id)
        {
            Addresses = addresses;
            DatabaseId = databaseId;
            Enabled = enabled;
            Id = id;
        }
    }
}
