// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Astra
{
    public static class GetKeyspaces
    {
        /// <summary>
        /// `astra.getKeyspaces` provides a datasource that lists the keyspaces in an Astra database.
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using Pulumi;
        /// using Astra = Pulumi.Astra;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var dev = Astra.GetKeyspaces.Invoke(new()
        ///     {
        ///         DatabaseId = "f9f4b1e0-4c05-451e-9bba-d631295a7f73",
        ///     });
        /// 
        /// });
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetKeyspacesResult> InvokeAsync(GetKeyspacesArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetKeyspacesResult>("astra:index/getKeyspaces:getKeyspaces", args ?? new GetKeyspacesArgs(), options.WithDefaults());

        /// <summary>
        /// `astra.getKeyspaces` provides a datasource that lists the keyspaces in an Astra database.
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using Pulumi;
        /// using Astra = Pulumi.Astra;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var dev = Astra.GetKeyspaces.Invoke(new()
        ///     {
        ///         DatabaseId = "f9f4b1e0-4c05-451e-9bba-d631295a7f73",
        ///     });
        /// 
        /// });
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Output<GetKeyspacesResult> Invoke(GetKeyspacesInvokeArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetKeyspacesResult>("astra:index/getKeyspaces:getKeyspaces", args ?? new GetKeyspacesInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetKeyspacesArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The ID of the Astra database.
        /// </summary>
        [Input("databaseId", required: true)]
        public string DatabaseId { get; set; } = null!;

        public GetKeyspacesArgs()
        {
        }
        public static new GetKeyspacesArgs Empty => new GetKeyspacesArgs();
    }

    public sealed class GetKeyspacesInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The ID of the Astra database.
        /// </summary>
        [Input("databaseId", required: true)]
        public Input<string> DatabaseId { get; set; } = null!;

        public GetKeyspacesInvokeArgs()
        {
        }
        public static new GetKeyspacesInvokeArgs Empty => new GetKeyspacesInvokeArgs();
    }


    [OutputType]
    public sealed class GetKeyspacesResult
    {
        /// <summary>
        /// The ID of the Astra database.
        /// </summary>
        public readonly string DatabaseId;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The list of keyspaces that match the search criteria.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetKeyspacesResultResult> Results;

        [OutputConstructor]
        private GetKeyspacesResult(
            string databaseId,

            string id,

            ImmutableArray<Outputs.GetKeyspacesResultResult> results)
        {
            DatabaseId = databaseId;
            Id = id;
            Results = results;
        }
    }
}
