// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Astra
{
    public static class GetPrivateLinkEndpoints
    {
        /// <summary>
        /// `astra.getPrivateLinkEndpoints` provides a datasource that lists the private link endpoints for an Astra database.
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using Pulumi;
        /// using Astra = Pulumi.Astra;
        /// 
        /// class MyStack : Stack
        /// {
        ///     public MyStack()
        ///     {
        ///         var dev = Output.Create(Astra.GetPrivateLinkEndpoints.InvokeAsync(new Astra.GetPrivateLinkEndpointsArgs
        ///         {
        ///             DatabaseId = "8d356587-73b3-430a-9c0e-d780332e2afb",
        ///             DatacenterId = "8d356587-73b3-430a-9c0e-d780332e2afb",
        ///             EndpointId = "com.amazonaws.vpce.us-east-1.vpce-svc-03ac5a4b18ee480df",
        ///         }));
        ///     }
        /// 
        /// }
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetPrivateLinkEndpointsResult> InvokeAsync(GetPrivateLinkEndpointsArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetPrivateLinkEndpointsResult>("astra:index/getPrivateLinkEndpoints:getPrivateLinkEndpoints", args ?? new GetPrivateLinkEndpointsArgs(), options.WithDefaults());

        /// <summary>
        /// `astra.getPrivateLinkEndpoints` provides a datasource that lists the private link endpoints for an Astra database.
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using Pulumi;
        /// using Astra = Pulumi.Astra;
        /// 
        /// class MyStack : Stack
        /// {
        ///     public MyStack()
        ///     {
        ///         var dev = Output.Create(Astra.GetPrivateLinkEndpoints.InvokeAsync(new Astra.GetPrivateLinkEndpointsArgs
        ///         {
        ///             DatabaseId = "8d356587-73b3-430a-9c0e-d780332e2afb",
        ///             DatacenterId = "8d356587-73b3-430a-9c0e-d780332e2afb",
        ///             EndpointId = "com.amazonaws.vpce.us-east-1.vpce-svc-03ac5a4b18ee480df",
        ///         }));
        ///     }
        /// 
        /// }
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Output<GetPrivateLinkEndpointsResult> Invoke(GetPrivateLinkEndpointsInvokeArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetPrivateLinkEndpointsResult>("astra:index/getPrivateLinkEndpoints:getPrivateLinkEndpoints", args ?? new GetPrivateLinkEndpointsInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetPrivateLinkEndpointsArgs : Pulumi.InvokeArgs
    {
        [Input("databaseId", required: true)]
        public string DatabaseId { get; set; } = null!;

        [Input("datacenterId", required: true)]
        public string DatacenterId { get; set; } = null!;

        [Input("endpointId", required: true)]
        public string EndpointId { get; set; } = null!;

        public GetPrivateLinkEndpointsArgs()
        {
        }
    }

    public sealed class GetPrivateLinkEndpointsInvokeArgs : Pulumi.InvokeArgs
    {
        [Input("databaseId", required: true)]
        public Input<string> DatabaseId { get; set; } = null!;

        [Input("datacenterId", required: true)]
        public Input<string> DatacenterId { get; set; } = null!;

        [Input("endpointId", required: true)]
        public Input<string> EndpointId { get; set; } = null!;

        public GetPrivateLinkEndpointsInvokeArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetPrivateLinkEndpointsResult
    {
        public readonly string DatabaseId;
        public readonly string DatacenterId;
        public readonly string EndpointId;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly ImmutableArray<Outputs.GetPrivateLinkEndpointsResultResult> Results;

        [OutputConstructor]
        private GetPrivateLinkEndpointsResult(
            string databaseId,

            string datacenterId,

            string endpointId,

            string id,

            ImmutableArray<Outputs.GetPrivateLinkEndpointsResultResult> results)
        {
            DatabaseId = databaseId;
            DatacenterId = datacenterId;
            EndpointId = endpointId;
            Id = id;
            Results = results;
        }
    }
}
