// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Astra
{
    public static class GetPrivateLinks
    {
        /// <summary>
        /// `astra.getPrivateLinks` provides a datasource that lists the private links in an Astra database.
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using Pulumi;
        /// using Astra = Pulumi.Astra;
        /// 
        /// class MyStack : Stack
        /// {
        ///     public MyStack()
        ///     {
        ///         var dev = Output.Create(Astra.GetPrivateLinks.InvokeAsync(new Astra.GetPrivateLinksArgs
        ///         {
        ///             DatabaseId = "a6bc9c26-e7ce-424f-84c7-0a00afb12588",
        ///             DatacenterId = "a6bc9c26-e7ce-424f-84c7-0a00afb12588",
        ///         }));
        ///     }
        /// 
        /// }
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetPrivateLinksResult> InvokeAsync(GetPrivateLinksArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetPrivateLinksResult>("astra:index/getPrivateLinks:getPrivateLinks", args ?? new GetPrivateLinksArgs(), options.WithDefaults());

        /// <summary>
        /// `astra.getPrivateLinks` provides a datasource that lists the private links in an Astra database.
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using Pulumi;
        /// using Astra = Pulumi.Astra;
        /// 
        /// class MyStack : Stack
        /// {
        ///     public MyStack()
        ///     {
        ///         var dev = Output.Create(Astra.GetPrivateLinks.InvokeAsync(new Astra.GetPrivateLinksArgs
        ///         {
        ///             DatabaseId = "a6bc9c26-e7ce-424f-84c7-0a00afb12588",
        ///             DatacenterId = "a6bc9c26-e7ce-424f-84c7-0a00afb12588",
        ///         }));
        ///     }
        /// 
        /// }
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Output<GetPrivateLinksResult> Invoke(GetPrivateLinksInvokeArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetPrivateLinksResult>("astra:index/getPrivateLinks:getPrivateLinks", args ?? new GetPrivateLinksInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetPrivateLinksArgs : Pulumi.InvokeArgs
    {
        [Input("databaseId", required: true)]
        public string DatabaseId { get; set; } = null!;

        [Input("datacenterId", required: true)]
        public string DatacenterId { get; set; } = null!;

        public GetPrivateLinksArgs()
        {
        }
    }

    public sealed class GetPrivateLinksInvokeArgs : Pulumi.InvokeArgs
    {
        [Input("databaseId", required: true)]
        public Input<string> DatabaseId { get; set; } = null!;

        [Input("datacenterId", required: true)]
        public Input<string> DatacenterId { get; set; } = null!;

        public GetPrivateLinksInvokeArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetPrivateLinksResult
    {
        public readonly string DatabaseId;
        public readonly string DatacenterId;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly ImmutableArray<Outputs.GetPrivateLinksResultResult> Results;

        [OutputConstructor]
        private GetPrivateLinksResult(
            string databaseId,

            string datacenterId,

            string id,

            ImmutableArray<Outputs.GetPrivateLinksResultResult> results)
        {
            DatabaseId = databaseId;
            DatacenterId = datacenterId;
            Id = id;
            Results = results;
        }
    }
}
