// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Astra.Astra.Outputs
{

    [OutputType]
    public sealed class GetAccessListResultResult
    {
        public readonly ImmutableArray<string> Addresses;
        public readonly string DatacenterId;
        public readonly string Enabled;
        public readonly string OrganizationId;

        [OutputConstructor]
        private GetAccessListResultResult(
            ImmutableArray<string> addresses,

            string datacenterId,

            string enabled,

            string organizationId)
        {
            Addresses = addresses;
            DatacenterId = datacenterId;
            Enabled = enabled;
            OrganizationId = organizationId;
        }
    }
}
