// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package index

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Retrieve a list of available cloud regions in Astra
//
// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// 	"github.com/pulumiverse/pulumi-index/sdk/go/index"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		_, err := astra.LookupAvailableRegions(ctx, nil, nil)
// 		if err != nil {
// 			return err
// 		}
// 		return nil
// 	})
// }
// ```
func LookupAvailableRegions(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*LookupAvailableRegionsResult, error) {
	opts = pkgInvokeDefaultOpts(opts)
	var rv LookupAvailableRegionsResult
	err := ctx.Invoke("astra:index/getAvailableRegions:getAvailableRegions", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getAvailableRegions.
type LookupAvailableRegionsResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id      string                      `pulumi:"id"`
	Results []GetAvailableRegionsResult `pulumi:"results"`
}
