// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package index

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "astra:index/accessList:AccessList":
		r = &AccessList{}
	case "astra:index/cdc:Cdc":
		r = &Cdc{}
	case "astra:index/database:Database":
		r = &Database{}
	case "astra:index/keyspace:Keyspace":
		r = &Keyspace{}
	case "astra:index/privateLink:PrivateLink":
		r = &PrivateLink{}
	case "astra:index/privateLinkEndpoint:PrivateLinkEndpoint":
		r = &PrivateLinkEndpoint{}
	case "astra:index/role:Role":
		r = &Role{}
	case "astra:index/streamingTenant:StreamingTenant":
		r = &StreamingTenant{}
	case "astra:index/token:Token":
		r = &Token{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

type pkg struct {
	version semver.Version
}

func (p *pkg) Version() semver.Version {
	return p.version
}

func (p *pkg) ConstructProvider(ctx *pulumi.Context, name, typ, urn string) (pulumi.ProviderResource, error) {
	if typ != "pulumi:providers:astra" {
		return nil, fmt.Errorf("unknown provider type: %s", typ)
	}

	r := &Provider{}
	err := ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return r, err
}

func init() {
	version, _ := PkgVersion()
	pulumi.RegisterResourceModule(
		"astra",
		"index/accessList",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"astra",
		"index/cdc",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"astra",
		"index/database",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"astra",
		"index/keyspace",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"astra",
		"index/privateLink",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"astra",
		"index/privateLinkEndpoint",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"astra",
		"index/role",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"astra",
		"index/streamingTenant",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"astra",
		"index/token",
		&module{version},
	)
	pulumi.RegisterResourcePackage(
		"astra",
		&pkg{version},
	)
}
