// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";
import * as utilities from "../utilities";

export function getAccessList(args: GetAccessListArgs, opts?: pulumi.InvokeOptions): Promise<GetAccessListResult> {
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("index:astra/getAccessList:getAccessList", {
        "databaseId": args.databaseId,
    }, opts);
}

/**
 * A collection of arguments for invoking getAccessList.
 */
export interface GetAccessListArgs {
    databaseId: string;
}

/**
 * A collection of values returned by getAccessList.
 */
export interface GetAccessListResult {
    readonly databaseId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly results: outputs.astra.GetAccessListResult[];
}

export function getAccessListOutput(args: GetAccessListOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetAccessListResult> {
    return pulumi.output(args).apply(a => getAccessList(a, opts))
}

/**
 * A collection of arguments for invoking getAccessList.
 */
export interface GetAccessListOutputArgs {
    databaseId: pulumi.Input<string>;
}
