// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export function getKeyspace(args: GetKeyspaceArgs, opts?: pulumi.InvokeOptions): Promise<GetKeyspaceResult> {
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("index:astra/getKeyspace:getKeyspace", {
        "databaseId": args.databaseId,
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getKeyspace.
 */
export interface GetKeyspaceArgs {
    databaseId: string;
    name: string;
}

/**
 * A collection of values returned by getKeyspace.
 */
export interface GetKeyspaceResult {
    readonly databaseId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
}

export function getKeyspaceOutput(args: GetKeyspaceOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetKeyspaceResult> {
    return pulumi.output(args).apply(a => getKeyspace(a, opts))
}

/**
 * A collection of arguments for invoking getKeyspace.
 */
export interface GetKeyspaceOutputArgs {
    databaseId: pulumi.Input<string>;
    name: pulumi.Input<string>;
}
