// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export function getSecureConnectBundleUrl(args: GetSecureConnectBundleUrlArgs, opts?: pulumi.InvokeOptions): Promise<GetSecureConnectBundleUrlResult> {
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("index:astra/getSecureConnectBundleUrl:getSecureConnectBundleUrl", {
        "databaseId": args.databaseId,
    }, opts);
}

/**
 * A collection of arguments for invoking getSecureConnectBundleUrl.
 */
export interface GetSecureConnectBundleUrlArgs {
    databaseId: string;
}

/**
 * A collection of values returned by getSecureConnectBundleUrl.
 */
export interface GetSecureConnectBundleUrlResult {
    readonly databaseId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly url: string;
}

export function getSecureConnectBundleUrlOutput(args: GetSecureConnectBundleUrlOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetSecureConnectBundleUrlResult> {
    return pulumi.output(args).apply(a => getSecureConnectBundleUrl(a, opts))
}

/**
 * A collection of arguments for invoking getSecureConnectBundleUrl.
 */
export interface GetSecureConnectBundleUrlOutputArgs {
    databaseId: pulumi.Input<string>;
}
