// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi.Utilities;

namespace Pulumi.Index.Astra
{
    public static class GetAccessList
    {
        public static Task<GetAccessListResult> InvokeAsync(GetAccessListArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetAccessListResult>("index:astra/getAccessList:getAccessList", args ?? new GetAccessListArgs(), options.WithVersion());

        public static Output<GetAccessListResult> Invoke(GetAccessListInvokeArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetAccessListResult>("index:astra/getAccessList:getAccessList", args ?? new GetAccessListInvokeArgs(), options.WithVersion());
    }


    public sealed class GetAccessListArgs : Pulumi.InvokeArgs
    {
        [Input("databaseId", required: true)]
        public string DatabaseId { get; set; } = null!;

        public GetAccessListArgs()
        {
        }
    }

    public sealed class GetAccessListInvokeArgs : Pulumi.InvokeArgs
    {
        [Input("databaseId", required: true)]
        public Input<string> DatabaseId { get; set; } = null!;

        public GetAccessListInvokeArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetAccessListResult
    {
        public readonly string DatabaseId;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly ImmutableArray<Outputs.GetAccessListResultResult> Results;

        [OutputConstructor]
        private GetAccessListResult(
            string databaseId,

            string id,

            ImmutableArray<Outputs.GetAccessListResultResult> results)
        {
            DatabaseId = databaseId;
            Id = id;
            Results = results;
        }
    }
}
