// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi.Utilities;

namespace Pulumi.Index.Astra
{
    public static class GetPrivateLinks
    {
        public static Task<GetPrivateLinksResult> InvokeAsync(GetPrivateLinksArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetPrivateLinksResult>("index:astra/getPrivateLinks:getPrivateLinks", args ?? new GetPrivateLinksArgs(), options.WithVersion());

        public static Output<GetPrivateLinksResult> Invoke(GetPrivateLinksInvokeArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetPrivateLinksResult>("index:astra/getPrivateLinks:getPrivateLinks", args ?? new GetPrivateLinksInvokeArgs(), options.WithVersion());
    }


    public sealed class GetPrivateLinksArgs : Pulumi.InvokeArgs
    {
        [Input("databaseId", required: true)]
        public string DatabaseId { get; set; } = null!;

        [Input("datacenterId", required: true)]
        public string DatacenterId { get; set; } = null!;

        public GetPrivateLinksArgs()
        {
        }
    }

    public sealed class GetPrivateLinksInvokeArgs : Pulumi.InvokeArgs
    {
        [Input("databaseId", required: true)]
        public Input<string> DatabaseId { get; set; } = null!;

        [Input("datacenterId", required: true)]
        public Input<string> DatacenterId { get; set; } = null!;

        public GetPrivateLinksInvokeArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetPrivateLinksResult
    {
        public readonly string DatabaseId;
        public readonly string DatacenterId;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly ImmutableArray<Outputs.GetPrivateLinksResultResult> Results;

        [OutputConstructor]
        private GetPrivateLinksResult(
            string databaseId,

            string datacenterId,

            string id,

            ImmutableArray<Outputs.GetPrivateLinksResultResult> results)
        {
            DatabaseId = databaseId;
            DatacenterId = datacenterId;
            Id = id;
            Results = results;
        }
    }
}
