// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi.Utilities;

namespace Pulumi.Index.Astra
{
    public static class GetSecureConnectBundleUrl
    {
        public static Task<GetSecureConnectBundleUrlResult> InvokeAsync(GetSecureConnectBundleUrlArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetSecureConnectBundleUrlResult>("index:astra/getSecureConnectBundleUrl:getSecureConnectBundleUrl", args ?? new GetSecureConnectBundleUrlArgs(), options.WithVersion());

        public static Output<GetSecureConnectBundleUrlResult> Invoke(GetSecureConnectBundleUrlInvokeArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetSecureConnectBundleUrlResult>("index:astra/getSecureConnectBundleUrl:getSecureConnectBundleUrl", args ?? new GetSecureConnectBundleUrlInvokeArgs(), options.WithVersion());
    }


    public sealed class GetSecureConnectBundleUrlArgs : Pulumi.InvokeArgs
    {
        [Input("databaseId", required: true)]
        public string DatabaseId { get; set; } = null!;

        public GetSecureConnectBundleUrlArgs()
        {
        }
    }

    public sealed class GetSecureConnectBundleUrlInvokeArgs : Pulumi.InvokeArgs
    {
        [Input("databaseId", required: true)]
        public Input<string> DatabaseId { get; set; } = null!;

        public GetSecureConnectBundleUrlInvokeArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetSecureConnectBundleUrlResult
    {
        public readonly string DatabaseId;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Url;

        [OutputConstructor]
        private GetSecureConnectBundleUrlResult(
            string databaseId,

            string id,

            string url)
        {
            DatabaseId = databaseId;
            Id = id;
            Url = url;
        }
    }
}
