// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Astra.Astra
{
    [AstraResourceType("index:astra/privateLinkEndpoint:PrivateLinkEndpoint")]
    public partial class PrivateLinkEndpoint : Pulumi.CustomResource
    {
        /// <summary>
        /// The ID of the Astra database.
        /// </summary>
        [Output("databaseId")]
        public Output<string> DatabaseId { get; private set; } = null!;

        /// <summary>
        /// Astra datacenter in the region where the private link will be created.
        /// </summary>
        [Output("datacenterId")]
        public Output<string> DatacenterId { get; private set; } = null!;

        /// <summary>
        /// Endpoint created in your cloud provider account example: "vpce-svc-1148ea04af8675309"
        /// </summary>
        [Output("endpointId")]
        public Output<string> EndpointId { get; private set; } = null!;


        /// <summary>
        /// Create a PrivateLinkEndpoint resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public PrivateLinkEndpoint(string name, PrivateLinkEndpointArgs args, CustomResourceOptions? options = null)
            : base("index:astra/privateLinkEndpoint:PrivateLinkEndpoint", name, args ?? new PrivateLinkEndpointArgs(), MakeResourceOptions(options, ""))
        {
        }

        private PrivateLinkEndpoint(string name, Input<string> id, PrivateLinkEndpointState? state = null, CustomResourceOptions? options = null)
            : base("index:astra/privateLinkEndpoint:PrivateLinkEndpoint", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing PrivateLinkEndpoint resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static PrivateLinkEndpoint Get(string name, Input<string> id, PrivateLinkEndpointState? state = null, CustomResourceOptions? options = null)
        {
            return new PrivateLinkEndpoint(name, id, state, options);
        }
    }

    public sealed class PrivateLinkEndpointArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The ID of the Astra database.
        /// </summary>
        [Input("databaseId", required: true)]
        public Input<string> DatabaseId { get; set; } = null!;

        /// <summary>
        /// Astra datacenter in the region where the private link will be created.
        /// </summary>
        [Input("datacenterId", required: true)]
        public Input<string> DatacenterId { get; set; } = null!;

        /// <summary>
        /// Endpoint created in your cloud provider account example: "vpce-svc-1148ea04af8675309"
        /// </summary>
        [Input("endpointId", required: true)]
        public Input<string> EndpointId { get; set; } = null!;

        public PrivateLinkEndpointArgs()
        {
        }
    }

    public sealed class PrivateLinkEndpointState : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The ID of the Astra database.
        /// </summary>
        [Input("databaseId")]
        public Input<string>? DatabaseId { get; set; }

        /// <summary>
        /// Astra datacenter in the region where the private link will be created.
        /// </summary>
        [Input("datacenterId")]
        public Input<string>? DatacenterId { get; set; }

        /// <summary>
        /// Endpoint created in your cloud provider account example: "vpce-svc-1148ea04af8675309"
        /// </summary>
        [Input("endpointId")]
        public Input<string>? EndpointId { get; set; }

        public PrivateLinkEndpointState()
        {
        }
    }
}
