// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package astra

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupKeyspaces(ctx *pulumi.Context, args *LookupKeyspacesArgs, opts ...pulumi.InvokeOption) (*LookupKeyspacesResult, error) {
	var rv LookupKeyspacesResult
	err := ctx.Invoke("index:astra/getKeyspaces:getKeyspaces", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getKeyspaces.
type LookupKeyspacesArgs struct {
	DatabaseId string `pulumi:"databaseId"`
}

// A collection of values returned by getKeyspaces.
type LookupKeyspacesResult struct {
	DatabaseId string `pulumi:"databaseId"`
	// The provider-assigned unique ID for this managed resource.
	Id      string               `pulumi:"id"`
	Results []GetKeyspacesResult `pulumi:"results"`
}

func LookupKeyspacesOutput(ctx *pulumi.Context, args LookupKeyspacesOutputArgs, opts ...pulumi.InvokeOption) LookupKeyspacesResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupKeyspacesResult, error) {
			args := v.(LookupKeyspacesArgs)
			r, err := LookupKeyspaces(ctx, &args, opts...)
			return *r, err
		}).(LookupKeyspacesResultOutput)
}

// A collection of arguments for invoking getKeyspaces.
type LookupKeyspacesOutputArgs struct {
	DatabaseId pulumi.StringInput `pulumi:"databaseId"`
}

func (LookupKeyspacesOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupKeyspacesArgs)(nil)).Elem()
}

// A collection of values returned by getKeyspaces.
type LookupKeyspacesResultOutput struct{ *pulumi.OutputState }

func (LookupKeyspacesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupKeyspacesResult)(nil)).Elem()
}

func (o LookupKeyspacesResultOutput) ToLookupKeyspacesResultOutput() LookupKeyspacesResultOutput {
	return o
}

func (o LookupKeyspacesResultOutput) ToLookupKeyspacesResultOutputWithContext(ctx context.Context) LookupKeyspacesResultOutput {
	return o
}

func (o LookupKeyspacesResultOutput) DatabaseId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupKeyspacesResult) string { return v.DatabaseId }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupKeyspacesResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupKeyspacesResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupKeyspacesResultOutput) Results() GetKeyspacesResultArrayOutput {
	return o.ApplyT(func(v LookupKeyspacesResult) []GetKeyspacesResult { return v.Results }).(GetKeyspacesResultArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupKeyspacesResultOutput{})
}
