// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package astra

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupPrivateLinkEndpoints(ctx *pulumi.Context, args *LookupPrivateLinkEndpointsArgs, opts ...pulumi.InvokeOption) (*LookupPrivateLinkEndpointsResult, error) {
	var rv LookupPrivateLinkEndpointsResult
	err := ctx.Invoke("index:astra/getPrivateLinkEndpoints:getPrivateLinkEndpoints", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getPrivateLinkEndpoints.
type LookupPrivateLinkEndpointsArgs struct {
	DatabaseId   string `pulumi:"databaseId"`
	DatacenterId string `pulumi:"datacenterId"`
	EndpointId   string `pulumi:"endpointId"`
}

// A collection of values returned by getPrivateLinkEndpoints.
type LookupPrivateLinkEndpointsResult struct {
	DatabaseId   string `pulumi:"databaseId"`
	DatacenterId string `pulumi:"datacenterId"`
	EndpointId   string `pulumi:"endpointId"`
	// The provider-assigned unique ID for this managed resource.
	Id      string                          `pulumi:"id"`
	Results []GetPrivateLinkEndpointsResult `pulumi:"results"`
}

func LookupPrivateLinkEndpointsOutput(ctx *pulumi.Context, args LookupPrivateLinkEndpointsOutputArgs, opts ...pulumi.InvokeOption) LookupPrivateLinkEndpointsResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupPrivateLinkEndpointsResult, error) {
			args := v.(LookupPrivateLinkEndpointsArgs)
			r, err := LookupPrivateLinkEndpoints(ctx, &args, opts...)
			return *r, err
		}).(LookupPrivateLinkEndpointsResultOutput)
}

// A collection of arguments for invoking getPrivateLinkEndpoints.
type LookupPrivateLinkEndpointsOutputArgs struct {
	DatabaseId   pulumi.StringInput `pulumi:"databaseId"`
	DatacenterId pulumi.StringInput `pulumi:"datacenterId"`
	EndpointId   pulumi.StringInput `pulumi:"endpointId"`
}

func (LookupPrivateLinkEndpointsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupPrivateLinkEndpointsArgs)(nil)).Elem()
}

// A collection of values returned by getPrivateLinkEndpoints.
type LookupPrivateLinkEndpointsResultOutput struct{ *pulumi.OutputState }

func (LookupPrivateLinkEndpointsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupPrivateLinkEndpointsResult)(nil)).Elem()
}

func (o LookupPrivateLinkEndpointsResultOutput) ToLookupPrivateLinkEndpointsResultOutput() LookupPrivateLinkEndpointsResultOutput {
	return o
}

func (o LookupPrivateLinkEndpointsResultOutput) ToLookupPrivateLinkEndpointsResultOutputWithContext(ctx context.Context) LookupPrivateLinkEndpointsResultOutput {
	return o
}

func (o LookupPrivateLinkEndpointsResultOutput) DatabaseId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupPrivateLinkEndpointsResult) string { return v.DatabaseId }).(pulumi.StringOutput)
}

func (o LookupPrivateLinkEndpointsResultOutput) DatacenterId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupPrivateLinkEndpointsResult) string { return v.DatacenterId }).(pulumi.StringOutput)
}

func (o LookupPrivateLinkEndpointsResultOutput) EndpointId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupPrivateLinkEndpointsResult) string { return v.EndpointId }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupPrivateLinkEndpointsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupPrivateLinkEndpointsResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupPrivateLinkEndpointsResultOutput) Results() GetPrivateLinkEndpointsResultArrayOutput {
	return o.ApplyT(func(v LookupPrivateLinkEndpointsResult) []GetPrivateLinkEndpointsResult { return v.Results }).(GetPrivateLinkEndpointsResultArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupPrivateLinkEndpointsResultOutput{})
}
