// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package astra

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type AccessListAddress struct {
	Requests []AccessListAddressRequest `pulumi:"requests"`
}

// AccessListAddressInput is an input type that accepts AccessListAddressArgs and AccessListAddressOutput values.
// You can construct a concrete instance of `AccessListAddressInput` via:
//
//          AccessListAddressArgs{...}
type AccessListAddressInput interface {
	pulumi.Input

	ToAccessListAddressOutput() AccessListAddressOutput
	ToAccessListAddressOutputWithContext(context.Context) AccessListAddressOutput
}

type AccessListAddressArgs struct {
	Requests AccessListAddressRequestArrayInput `pulumi:"requests"`
}

func (AccessListAddressArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*AccessListAddress)(nil)).Elem()
}

func (i AccessListAddressArgs) ToAccessListAddressOutput() AccessListAddressOutput {
	return i.ToAccessListAddressOutputWithContext(context.Background())
}

func (i AccessListAddressArgs) ToAccessListAddressOutputWithContext(ctx context.Context) AccessListAddressOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AccessListAddressOutput)
}

// AccessListAddressArrayInput is an input type that accepts AccessListAddressArray and AccessListAddressArrayOutput values.
// You can construct a concrete instance of `AccessListAddressArrayInput` via:
//
//          AccessListAddressArray{ AccessListAddressArgs{...} }
type AccessListAddressArrayInput interface {
	pulumi.Input

	ToAccessListAddressArrayOutput() AccessListAddressArrayOutput
	ToAccessListAddressArrayOutputWithContext(context.Context) AccessListAddressArrayOutput
}

type AccessListAddressArray []AccessListAddressInput

func (AccessListAddressArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]AccessListAddress)(nil)).Elem()
}

func (i AccessListAddressArray) ToAccessListAddressArrayOutput() AccessListAddressArrayOutput {
	return i.ToAccessListAddressArrayOutputWithContext(context.Background())
}

func (i AccessListAddressArray) ToAccessListAddressArrayOutputWithContext(ctx context.Context) AccessListAddressArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AccessListAddressArrayOutput)
}

type AccessListAddressOutput struct{ *pulumi.OutputState }

func (AccessListAddressOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*AccessListAddress)(nil)).Elem()
}

func (o AccessListAddressOutput) ToAccessListAddressOutput() AccessListAddressOutput {
	return o
}

func (o AccessListAddressOutput) ToAccessListAddressOutputWithContext(ctx context.Context) AccessListAddressOutput {
	return o
}

func (o AccessListAddressOutput) Requests() AccessListAddressRequestArrayOutput {
	return o.ApplyT(func(v AccessListAddress) []AccessListAddressRequest { return v.Requests }).(AccessListAddressRequestArrayOutput)
}

type AccessListAddressArrayOutput struct{ *pulumi.OutputState }

func (AccessListAddressArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]AccessListAddress)(nil)).Elem()
}

func (o AccessListAddressArrayOutput) ToAccessListAddressArrayOutput() AccessListAddressArrayOutput {
	return o
}

func (o AccessListAddressArrayOutput) ToAccessListAddressArrayOutputWithContext(ctx context.Context) AccessListAddressArrayOutput {
	return o
}

func (o AccessListAddressArrayOutput) Index(i pulumi.IntInput) AccessListAddressOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) AccessListAddress {
		return vs[0].([]AccessListAddress)[vs[1].(int)]
	}).(AccessListAddressOutput)
}

type AccessListAddressRequest struct {
	Address     string  `pulumi:"address"`
	Description *string `pulumi:"description"`
	Enabled     bool    `pulumi:"enabled"`
}

// AccessListAddressRequestInput is an input type that accepts AccessListAddressRequestArgs and AccessListAddressRequestOutput values.
// You can construct a concrete instance of `AccessListAddressRequestInput` via:
//
//          AccessListAddressRequestArgs{...}
type AccessListAddressRequestInput interface {
	pulumi.Input

	ToAccessListAddressRequestOutput() AccessListAddressRequestOutput
	ToAccessListAddressRequestOutputWithContext(context.Context) AccessListAddressRequestOutput
}

type AccessListAddressRequestArgs struct {
	Address     pulumi.StringInput    `pulumi:"address"`
	Description pulumi.StringPtrInput `pulumi:"description"`
	Enabled     pulumi.BoolInput      `pulumi:"enabled"`
}

func (AccessListAddressRequestArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*AccessListAddressRequest)(nil)).Elem()
}

func (i AccessListAddressRequestArgs) ToAccessListAddressRequestOutput() AccessListAddressRequestOutput {
	return i.ToAccessListAddressRequestOutputWithContext(context.Background())
}

func (i AccessListAddressRequestArgs) ToAccessListAddressRequestOutputWithContext(ctx context.Context) AccessListAddressRequestOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AccessListAddressRequestOutput)
}

// AccessListAddressRequestArrayInput is an input type that accepts AccessListAddressRequestArray and AccessListAddressRequestArrayOutput values.
// You can construct a concrete instance of `AccessListAddressRequestArrayInput` via:
//
//          AccessListAddressRequestArray{ AccessListAddressRequestArgs{...} }
type AccessListAddressRequestArrayInput interface {
	pulumi.Input

	ToAccessListAddressRequestArrayOutput() AccessListAddressRequestArrayOutput
	ToAccessListAddressRequestArrayOutputWithContext(context.Context) AccessListAddressRequestArrayOutput
}

type AccessListAddressRequestArray []AccessListAddressRequestInput

func (AccessListAddressRequestArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]AccessListAddressRequest)(nil)).Elem()
}

func (i AccessListAddressRequestArray) ToAccessListAddressRequestArrayOutput() AccessListAddressRequestArrayOutput {
	return i.ToAccessListAddressRequestArrayOutputWithContext(context.Background())
}

func (i AccessListAddressRequestArray) ToAccessListAddressRequestArrayOutputWithContext(ctx context.Context) AccessListAddressRequestArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AccessListAddressRequestArrayOutput)
}

type AccessListAddressRequestOutput struct{ *pulumi.OutputState }

func (AccessListAddressRequestOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*AccessListAddressRequest)(nil)).Elem()
}

func (o AccessListAddressRequestOutput) ToAccessListAddressRequestOutput() AccessListAddressRequestOutput {
	return o
}

func (o AccessListAddressRequestOutput) ToAccessListAddressRequestOutputWithContext(ctx context.Context) AccessListAddressRequestOutput {
	return o
}

func (o AccessListAddressRequestOutput) Address() pulumi.StringOutput {
	return o.ApplyT(func(v AccessListAddressRequest) string { return v.Address }).(pulumi.StringOutput)
}

func (o AccessListAddressRequestOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v AccessListAddressRequest) *string { return v.Description }).(pulumi.StringPtrOutput)
}

func (o AccessListAddressRequestOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v AccessListAddressRequest) bool { return v.Enabled }).(pulumi.BoolOutput)
}

type AccessListAddressRequestArrayOutput struct{ *pulumi.OutputState }

func (AccessListAddressRequestArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]AccessListAddressRequest)(nil)).Elem()
}

func (o AccessListAddressRequestArrayOutput) ToAccessListAddressRequestArrayOutput() AccessListAddressRequestArrayOutput {
	return o
}

func (o AccessListAddressRequestArrayOutput) ToAccessListAddressRequestArrayOutputWithContext(ctx context.Context) AccessListAddressRequestArrayOutput {
	return o
}

func (o AccessListAddressRequestArrayOutput) Index(i pulumi.IntInput) AccessListAddressRequestOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) AccessListAddressRequest {
		return vs[0].([]AccessListAddressRequest)[vs[1].(int)]
	}).(AccessListAddressRequestOutput)
}

type GetAccessListResult struct {
	Addresses      []string `pulumi:"addresses"`
	DatacenterId   string   `pulumi:"datacenterId"`
	Enabled        string   `pulumi:"enabled"`
	OrganizationId string   `pulumi:"organizationId"`
}

// GetAccessListResultInput is an input type that accepts GetAccessListResultArgs and GetAccessListResultOutput values.
// You can construct a concrete instance of `GetAccessListResultInput` via:
//
//          GetAccessListResultArgs{...}
type GetAccessListResultInput interface {
	pulumi.Input

	ToGetAccessListResultOutput() GetAccessListResultOutput
	ToGetAccessListResultOutputWithContext(context.Context) GetAccessListResultOutput
}

type GetAccessListResultArgs struct {
	Addresses      pulumi.StringArrayInput `pulumi:"addresses"`
	DatacenterId   pulumi.StringInput      `pulumi:"datacenterId"`
	Enabled        pulumi.StringInput      `pulumi:"enabled"`
	OrganizationId pulumi.StringInput      `pulumi:"organizationId"`
}

func (GetAccessListResultArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetAccessListResult)(nil)).Elem()
}

func (i GetAccessListResultArgs) ToGetAccessListResultOutput() GetAccessListResultOutput {
	return i.ToGetAccessListResultOutputWithContext(context.Background())
}

func (i GetAccessListResultArgs) ToGetAccessListResultOutputWithContext(ctx context.Context) GetAccessListResultOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetAccessListResultOutput)
}

// GetAccessListResultArrayInput is an input type that accepts GetAccessListResultArray and GetAccessListResultArrayOutput values.
// You can construct a concrete instance of `GetAccessListResultArrayInput` via:
//
//          GetAccessListResultArray{ GetAccessListResultArgs{...} }
type GetAccessListResultArrayInput interface {
	pulumi.Input

	ToGetAccessListResultArrayOutput() GetAccessListResultArrayOutput
	ToGetAccessListResultArrayOutputWithContext(context.Context) GetAccessListResultArrayOutput
}

type GetAccessListResultArray []GetAccessListResultInput

func (GetAccessListResultArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetAccessListResult)(nil)).Elem()
}

func (i GetAccessListResultArray) ToGetAccessListResultArrayOutput() GetAccessListResultArrayOutput {
	return i.ToGetAccessListResultArrayOutputWithContext(context.Background())
}

func (i GetAccessListResultArray) ToGetAccessListResultArrayOutputWithContext(ctx context.Context) GetAccessListResultArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetAccessListResultArrayOutput)
}

type GetAccessListResultOutput struct{ *pulumi.OutputState }

func (GetAccessListResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetAccessListResult)(nil)).Elem()
}

func (o GetAccessListResultOutput) ToGetAccessListResultOutput() GetAccessListResultOutput {
	return o
}

func (o GetAccessListResultOutput) ToGetAccessListResultOutputWithContext(ctx context.Context) GetAccessListResultOutput {
	return o
}

func (o GetAccessListResultOutput) Addresses() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetAccessListResult) []string { return v.Addresses }).(pulumi.StringArrayOutput)
}

func (o GetAccessListResultOutput) DatacenterId() pulumi.StringOutput {
	return o.ApplyT(func(v GetAccessListResult) string { return v.DatacenterId }).(pulumi.StringOutput)
}

func (o GetAccessListResultOutput) Enabled() pulumi.StringOutput {
	return o.ApplyT(func(v GetAccessListResult) string { return v.Enabled }).(pulumi.StringOutput)
}

func (o GetAccessListResultOutput) OrganizationId() pulumi.StringOutput {
	return o.ApplyT(func(v GetAccessListResult) string { return v.OrganizationId }).(pulumi.StringOutput)
}

type GetAccessListResultArrayOutput struct{ *pulumi.OutputState }

func (GetAccessListResultArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetAccessListResult)(nil)).Elem()
}

func (o GetAccessListResultArrayOutput) ToGetAccessListResultArrayOutput() GetAccessListResultArrayOutput {
	return o
}

func (o GetAccessListResultArrayOutput) ToGetAccessListResultArrayOutputWithContext(ctx context.Context) GetAccessListResultArrayOutput {
	return o
}

func (o GetAccessListResultArrayOutput) Index(i pulumi.IntInput) GetAccessListResultOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetAccessListResult {
		return vs[0].([]GetAccessListResult)[vs[1].(int)]
	}).(GetAccessListResultOutput)
}

type GetAstraDatabasesResult struct {
	AdditionalKeyspaces []string `pulumi:"additionalKeyspaces"`
	CloudProvider       string   `pulumi:"cloudProvider"`
	CqlshUrl            string   `pulumi:"cqlshUrl"`
	DataEndpointUrl     string   `pulumi:"dataEndpointUrl"`
	GrafanaUrl          string   `pulumi:"grafanaUrl"`
	GraphqlUrl          string   `pulumi:"graphqlUrl"`
	Id                  string   `pulumi:"id"`
	Keyspace            string   `pulumi:"keyspace"`
	Name                string   `pulumi:"name"`
	NodeCount           int      `pulumi:"nodeCount"`
	OrganizationId      string   `pulumi:"organizationId"`
	OwnerId             string   `pulumi:"ownerId"`
	Regions             []string `pulumi:"regions"`
	ReplicationFactor   int      `pulumi:"replicationFactor"`
	Status              string   `pulumi:"status"`
	TotalStorage        int      `pulumi:"totalStorage"`
}

// GetAstraDatabasesResultInput is an input type that accepts GetAstraDatabasesResultArgs and GetAstraDatabasesResultOutput values.
// You can construct a concrete instance of `GetAstraDatabasesResultInput` via:
//
//          GetAstraDatabasesResultArgs{...}
type GetAstraDatabasesResultInput interface {
	pulumi.Input

	ToGetAstraDatabasesResultOutput() GetAstraDatabasesResultOutput
	ToGetAstraDatabasesResultOutputWithContext(context.Context) GetAstraDatabasesResultOutput
}

type GetAstraDatabasesResultArgs struct {
	AdditionalKeyspaces pulumi.StringArrayInput `pulumi:"additionalKeyspaces"`
	CloudProvider       pulumi.StringInput      `pulumi:"cloudProvider"`
	CqlshUrl            pulumi.StringInput      `pulumi:"cqlshUrl"`
	DataEndpointUrl     pulumi.StringInput      `pulumi:"dataEndpointUrl"`
	GrafanaUrl          pulumi.StringInput      `pulumi:"grafanaUrl"`
	GraphqlUrl          pulumi.StringInput      `pulumi:"graphqlUrl"`
	Id                  pulumi.StringInput      `pulumi:"id"`
	Keyspace            pulumi.StringInput      `pulumi:"keyspace"`
	Name                pulumi.StringInput      `pulumi:"name"`
	NodeCount           pulumi.IntInput         `pulumi:"nodeCount"`
	OrganizationId      pulumi.StringInput      `pulumi:"organizationId"`
	OwnerId             pulumi.StringInput      `pulumi:"ownerId"`
	Regions             pulumi.StringArrayInput `pulumi:"regions"`
	ReplicationFactor   pulumi.IntInput         `pulumi:"replicationFactor"`
	Status              pulumi.StringInput      `pulumi:"status"`
	TotalStorage        pulumi.IntInput         `pulumi:"totalStorage"`
}

func (GetAstraDatabasesResultArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetAstraDatabasesResult)(nil)).Elem()
}

func (i GetAstraDatabasesResultArgs) ToGetAstraDatabasesResultOutput() GetAstraDatabasesResultOutput {
	return i.ToGetAstraDatabasesResultOutputWithContext(context.Background())
}

func (i GetAstraDatabasesResultArgs) ToGetAstraDatabasesResultOutputWithContext(ctx context.Context) GetAstraDatabasesResultOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetAstraDatabasesResultOutput)
}

// GetAstraDatabasesResultArrayInput is an input type that accepts GetAstraDatabasesResultArray and GetAstraDatabasesResultArrayOutput values.
// You can construct a concrete instance of `GetAstraDatabasesResultArrayInput` via:
//
//          GetAstraDatabasesResultArray{ GetAstraDatabasesResultArgs{...} }
type GetAstraDatabasesResultArrayInput interface {
	pulumi.Input

	ToGetAstraDatabasesResultArrayOutput() GetAstraDatabasesResultArrayOutput
	ToGetAstraDatabasesResultArrayOutputWithContext(context.Context) GetAstraDatabasesResultArrayOutput
}

type GetAstraDatabasesResultArray []GetAstraDatabasesResultInput

func (GetAstraDatabasesResultArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetAstraDatabasesResult)(nil)).Elem()
}

func (i GetAstraDatabasesResultArray) ToGetAstraDatabasesResultArrayOutput() GetAstraDatabasesResultArrayOutput {
	return i.ToGetAstraDatabasesResultArrayOutputWithContext(context.Background())
}

func (i GetAstraDatabasesResultArray) ToGetAstraDatabasesResultArrayOutputWithContext(ctx context.Context) GetAstraDatabasesResultArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetAstraDatabasesResultArrayOutput)
}

type GetAstraDatabasesResultOutput struct{ *pulumi.OutputState }

func (GetAstraDatabasesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetAstraDatabasesResult)(nil)).Elem()
}

func (o GetAstraDatabasesResultOutput) ToGetAstraDatabasesResultOutput() GetAstraDatabasesResultOutput {
	return o
}

func (o GetAstraDatabasesResultOutput) ToGetAstraDatabasesResultOutputWithContext(ctx context.Context) GetAstraDatabasesResultOutput {
	return o
}

func (o GetAstraDatabasesResultOutput) AdditionalKeyspaces() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetAstraDatabasesResult) []string { return v.AdditionalKeyspaces }).(pulumi.StringArrayOutput)
}

func (o GetAstraDatabasesResultOutput) CloudProvider() pulumi.StringOutput {
	return o.ApplyT(func(v GetAstraDatabasesResult) string { return v.CloudProvider }).(pulumi.StringOutput)
}

func (o GetAstraDatabasesResultOutput) CqlshUrl() pulumi.StringOutput {
	return o.ApplyT(func(v GetAstraDatabasesResult) string { return v.CqlshUrl }).(pulumi.StringOutput)
}

func (o GetAstraDatabasesResultOutput) DataEndpointUrl() pulumi.StringOutput {
	return o.ApplyT(func(v GetAstraDatabasesResult) string { return v.DataEndpointUrl }).(pulumi.StringOutput)
}

func (o GetAstraDatabasesResultOutput) GrafanaUrl() pulumi.StringOutput {
	return o.ApplyT(func(v GetAstraDatabasesResult) string { return v.GrafanaUrl }).(pulumi.StringOutput)
}

func (o GetAstraDatabasesResultOutput) GraphqlUrl() pulumi.StringOutput {
	return o.ApplyT(func(v GetAstraDatabasesResult) string { return v.GraphqlUrl }).(pulumi.StringOutput)
}

func (o GetAstraDatabasesResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetAstraDatabasesResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetAstraDatabasesResultOutput) Keyspace() pulumi.StringOutput {
	return o.ApplyT(func(v GetAstraDatabasesResult) string { return v.Keyspace }).(pulumi.StringOutput)
}

func (o GetAstraDatabasesResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetAstraDatabasesResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o GetAstraDatabasesResultOutput) NodeCount() pulumi.IntOutput {
	return o.ApplyT(func(v GetAstraDatabasesResult) int { return v.NodeCount }).(pulumi.IntOutput)
}

func (o GetAstraDatabasesResultOutput) OrganizationId() pulumi.StringOutput {
	return o.ApplyT(func(v GetAstraDatabasesResult) string { return v.OrganizationId }).(pulumi.StringOutput)
}

func (o GetAstraDatabasesResultOutput) OwnerId() pulumi.StringOutput {
	return o.ApplyT(func(v GetAstraDatabasesResult) string { return v.OwnerId }).(pulumi.StringOutput)
}

func (o GetAstraDatabasesResultOutput) Regions() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetAstraDatabasesResult) []string { return v.Regions }).(pulumi.StringArrayOutput)
}

func (o GetAstraDatabasesResultOutput) ReplicationFactor() pulumi.IntOutput {
	return o.ApplyT(func(v GetAstraDatabasesResult) int { return v.ReplicationFactor }).(pulumi.IntOutput)
}

func (o GetAstraDatabasesResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v GetAstraDatabasesResult) string { return v.Status }).(pulumi.StringOutput)
}

func (o GetAstraDatabasesResultOutput) TotalStorage() pulumi.IntOutput {
	return o.ApplyT(func(v GetAstraDatabasesResult) int { return v.TotalStorage }).(pulumi.IntOutput)
}

type GetAstraDatabasesResultArrayOutput struct{ *pulumi.OutputState }

func (GetAstraDatabasesResultArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetAstraDatabasesResult)(nil)).Elem()
}

func (o GetAstraDatabasesResultArrayOutput) ToGetAstraDatabasesResultArrayOutput() GetAstraDatabasesResultArrayOutput {
	return o
}

func (o GetAstraDatabasesResultArrayOutput) ToGetAstraDatabasesResultArrayOutputWithContext(ctx context.Context) GetAstraDatabasesResultArrayOutput {
	return o
}

func (o GetAstraDatabasesResultArrayOutput) Index(i pulumi.IntInput) GetAstraDatabasesResultOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetAstraDatabasesResult {
		return vs[0].([]GetAstraDatabasesResult)[vs[1].(int)]
	}).(GetAstraDatabasesResultOutput)
}

type GetAvailableRegionsResult struct {
	CloudProvider string `pulumi:"cloudProvider"`
	DisplayName   string `pulumi:"displayName"`
	Region        string `pulumi:"region"`
	Zone          string `pulumi:"zone"`
}

// GetAvailableRegionsResultInput is an input type that accepts GetAvailableRegionsResultArgs and GetAvailableRegionsResultOutput values.
// You can construct a concrete instance of `GetAvailableRegionsResultInput` via:
//
//          GetAvailableRegionsResultArgs{...}
type GetAvailableRegionsResultInput interface {
	pulumi.Input

	ToGetAvailableRegionsResultOutput() GetAvailableRegionsResultOutput
	ToGetAvailableRegionsResultOutputWithContext(context.Context) GetAvailableRegionsResultOutput
}

type GetAvailableRegionsResultArgs struct {
	CloudProvider pulumi.StringInput `pulumi:"cloudProvider"`
	DisplayName   pulumi.StringInput `pulumi:"displayName"`
	Region        pulumi.StringInput `pulumi:"region"`
	Zone          pulumi.StringInput `pulumi:"zone"`
}

func (GetAvailableRegionsResultArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetAvailableRegionsResult)(nil)).Elem()
}

func (i GetAvailableRegionsResultArgs) ToGetAvailableRegionsResultOutput() GetAvailableRegionsResultOutput {
	return i.ToGetAvailableRegionsResultOutputWithContext(context.Background())
}

func (i GetAvailableRegionsResultArgs) ToGetAvailableRegionsResultOutputWithContext(ctx context.Context) GetAvailableRegionsResultOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetAvailableRegionsResultOutput)
}

// GetAvailableRegionsResultArrayInput is an input type that accepts GetAvailableRegionsResultArray and GetAvailableRegionsResultArrayOutput values.
// You can construct a concrete instance of `GetAvailableRegionsResultArrayInput` via:
//
//          GetAvailableRegionsResultArray{ GetAvailableRegionsResultArgs{...} }
type GetAvailableRegionsResultArrayInput interface {
	pulumi.Input

	ToGetAvailableRegionsResultArrayOutput() GetAvailableRegionsResultArrayOutput
	ToGetAvailableRegionsResultArrayOutputWithContext(context.Context) GetAvailableRegionsResultArrayOutput
}

type GetAvailableRegionsResultArray []GetAvailableRegionsResultInput

func (GetAvailableRegionsResultArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetAvailableRegionsResult)(nil)).Elem()
}

func (i GetAvailableRegionsResultArray) ToGetAvailableRegionsResultArrayOutput() GetAvailableRegionsResultArrayOutput {
	return i.ToGetAvailableRegionsResultArrayOutputWithContext(context.Background())
}

func (i GetAvailableRegionsResultArray) ToGetAvailableRegionsResultArrayOutputWithContext(ctx context.Context) GetAvailableRegionsResultArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetAvailableRegionsResultArrayOutput)
}

type GetAvailableRegionsResultOutput struct{ *pulumi.OutputState }

func (GetAvailableRegionsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetAvailableRegionsResult)(nil)).Elem()
}

func (o GetAvailableRegionsResultOutput) ToGetAvailableRegionsResultOutput() GetAvailableRegionsResultOutput {
	return o
}

func (o GetAvailableRegionsResultOutput) ToGetAvailableRegionsResultOutputWithContext(ctx context.Context) GetAvailableRegionsResultOutput {
	return o
}

func (o GetAvailableRegionsResultOutput) CloudProvider() pulumi.StringOutput {
	return o.ApplyT(func(v GetAvailableRegionsResult) string { return v.CloudProvider }).(pulumi.StringOutput)
}

func (o GetAvailableRegionsResultOutput) DisplayName() pulumi.StringOutput {
	return o.ApplyT(func(v GetAvailableRegionsResult) string { return v.DisplayName }).(pulumi.StringOutput)
}

func (o GetAvailableRegionsResultOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v GetAvailableRegionsResult) string { return v.Region }).(pulumi.StringOutput)
}

func (o GetAvailableRegionsResultOutput) Zone() pulumi.StringOutput {
	return o.ApplyT(func(v GetAvailableRegionsResult) string { return v.Zone }).(pulumi.StringOutput)
}

type GetAvailableRegionsResultArrayOutput struct{ *pulumi.OutputState }

func (GetAvailableRegionsResultArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetAvailableRegionsResult)(nil)).Elem()
}

func (o GetAvailableRegionsResultArrayOutput) ToGetAvailableRegionsResultArrayOutput() GetAvailableRegionsResultArrayOutput {
	return o
}

func (o GetAvailableRegionsResultArrayOutput) ToGetAvailableRegionsResultArrayOutputWithContext(ctx context.Context) GetAvailableRegionsResultArrayOutput {
	return o
}

func (o GetAvailableRegionsResultArrayOutput) Index(i pulumi.IntInput) GetAvailableRegionsResultOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetAvailableRegionsResult {
		return vs[0].([]GetAvailableRegionsResult)[vs[1].(int)]
	}).(GetAvailableRegionsResultOutput)
}

type GetKeyspacesResult struct {
	Name string `pulumi:"name"`
}

// GetKeyspacesResultInput is an input type that accepts GetKeyspacesResultArgs and GetKeyspacesResultOutput values.
// You can construct a concrete instance of `GetKeyspacesResultInput` via:
//
//          GetKeyspacesResultArgs{...}
type GetKeyspacesResultInput interface {
	pulumi.Input

	ToGetKeyspacesResultOutput() GetKeyspacesResultOutput
	ToGetKeyspacesResultOutputWithContext(context.Context) GetKeyspacesResultOutput
}

type GetKeyspacesResultArgs struct {
	Name pulumi.StringInput `pulumi:"name"`
}

func (GetKeyspacesResultArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetKeyspacesResult)(nil)).Elem()
}

func (i GetKeyspacesResultArgs) ToGetKeyspacesResultOutput() GetKeyspacesResultOutput {
	return i.ToGetKeyspacesResultOutputWithContext(context.Background())
}

func (i GetKeyspacesResultArgs) ToGetKeyspacesResultOutputWithContext(ctx context.Context) GetKeyspacesResultOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetKeyspacesResultOutput)
}

// GetKeyspacesResultArrayInput is an input type that accepts GetKeyspacesResultArray and GetKeyspacesResultArrayOutput values.
// You can construct a concrete instance of `GetKeyspacesResultArrayInput` via:
//
//          GetKeyspacesResultArray{ GetKeyspacesResultArgs{...} }
type GetKeyspacesResultArrayInput interface {
	pulumi.Input

	ToGetKeyspacesResultArrayOutput() GetKeyspacesResultArrayOutput
	ToGetKeyspacesResultArrayOutputWithContext(context.Context) GetKeyspacesResultArrayOutput
}

type GetKeyspacesResultArray []GetKeyspacesResultInput

func (GetKeyspacesResultArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetKeyspacesResult)(nil)).Elem()
}

func (i GetKeyspacesResultArray) ToGetKeyspacesResultArrayOutput() GetKeyspacesResultArrayOutput {
	return i.ToGetKeyspacesResultArrayOutputWithContext(context.Background())
}

func (i GetKeyspacesResultArray) ToGetKeyspacesResultArrayOutputWithContext(ctx context.Context) GetKeyspacesResultArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetKeyspacesResultArrayOutput)
}

type GetKeyspacesResultOutput struct{ *pulumi.OutputState }

func (GetKeyspacesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetKeyspacesResult)(nil)).Elem()
}

func (o GetKeyspacesResultOutput) ToGetKeyspacesResultOutput() GetKeyspacesResultOutput {
	return o
}

func (o GetKeyspacesResultOutput) ToGetKeyspacesResultOutputWithContext(ctx context.Context) GetKeyspacesResultOutput {
	return o
}

func (o GetKeyspacesResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetKeyspacesResult) string { return v.Name }).(pulumi.StringOutput)
}

type GetKeyspacesResultArrayOutput struct{ *pulumi.OutputState }

func (GetKeyspacesResultArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetKeyspacesResult)(nil)).Elem()
}

func (o GetKeyspacesResultArrayOutput) ToGetKeyspacesResultArrayOutput() GetKeyspacesResultArrayOutput {
	return o
}

func (o GetKeyspacesResultArrayOutput) ToGetKeyspacesResultArrayOutputWithContext(ctx context.Context) GetKeyspacesResultArrayOutput {
	return o
}

func (o GetKeyspacesResultArrayOutput) Index(i pulumi.IntInput) GetKeyspacesResultOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetKeyspacesResult {
		return vs[0].([]GetKeyspacesResult)[vs[1].(int)]
	}).(GetKeyspacesResultOutput)
}

type GetPrivateLinkEndpointsResult struct {
	CreateTime  string `pulumi:"createTime"`
	Description string `pulumi:"description"`
	EndpointId  string `pulumi:"endpointId"`
	Status      string `pulumi:"status"`
}

// GetPrivateLinkEndpointsResultInput is an input type that accepts GetPrivateLinkEndpointsResultArgs and GetPrivateLinkEndpointsResultOutput values.
// You can construct a concrete instance of `GetPrivateLinkEndpointsResultInput` via:
//
//          GetPrivateLinkEndpointsResultArgs{...}
type GetPrivateLinkEndpointsResultInput interface {
	pulumi.Input

	ToGetPrivateLinkEndpointsResultOutput() GetPrivateLinkEndpointsResultOutput
	ToGetPrivateLinkEndpointsResultOutputWithContext(context.Context) GetPrivateLinkEndpointsResultOutput
}

type GetPrivateLinkEndpointsResultArgs struct {
	CreateTime  pulumi.StringInput `pulumi:"createTime"`
	Description pulumi.StringInput `pulumi:"description"`
	EndpointId  pulumi.StringInput `pulumi:"endpointId"`
	Status      pulumi.StringInput `pulumi:"status"`
}

func (GetPrivateLinkEndpointsResultArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPrivateLinkEndpointsResult)(nil)).Elem()
}

func (i GetPrivateLinkEndpointsResultArgs) ToGetPrivateLinkEndpointsResultOutput() GetPrivateLinkEndpointsResultOutput {
	return i.ToGetPrivateLinkEndpointsResultOutputWithContext(context.Background())
}

func (i GetPrivateLinkEndpointsResultArgs) ToGetPrivateLinkEndpointsResultOutputWithContext(ctx context.Context) GetPrivateLinkEndpointsResultOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetPrivateLinkEndpointsResultOutput)
}

// GetPrivateLinkEndpointsResultArrayInput is an input type that accepts GetPrivateLinkEndpointsResultArray and GetPrivateLinkEndpointsResultArrayOutput values.
// You can construct a concrete instance of `GetPrivateLinkEndpointsResultArrayInput` via:
//
//          GetPrivateLinkEndpointsResultArray{ GetPrivateLinkEndpointsResultArgs{...} }
type GetPrivateLinkEndpointsResultArrayInput interface {
	pulumi.Input

	ToGetPrivateLinkEndpointsResultArrayOutput() GetPrivateLinkEndpointsResultArrayOutput
	ToGetPrivateLinkEndpointsResultArrayOutputWithContext(context.Context) GetPrivateLinkEndpointsResultArrayOutput
}

type GetPrivateLinkEndpointsResultArray []GetPrivateLinkEndpointsResultInput

func (GetPrivateLinkEndpointsResultArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetPrivateLinkEndpointsResult)(nil)).Elem()
}

func (i GetPrivateLinkEndpointsResultArray) ToGetPrivateLinkEndpointsResultArrayOutput() GetPrivateLinkEndpointsResultArrayOutput {
	return i.ToGetPrivateLinkEndpointsResultArrayOutputWithContext(context.Background())
}

func (i GetPrivateLinkEndpointsResultArray) ToGetPrivateLinkEndpointsResultArrayOutputWithContext(ctx context.Context) GetPrivateLinkEndpointsResultArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetPrivateLinkEndpointsResultArrayOutput)
}

type GetPrivateLinkEndpointsResultOutput struct{ *pulumi.OutputState }

func (GetPrivateLinkEndpointsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPrivateLinkEndpointsResult)(nil)).Elem()
}

func (o GetPrivateLinkEndpointsResultOutput) ToGetPrivateLinkEndpointsResultOutput() GetPrivateLinkEndpointsResultOutput {
	return o
}

func (o GetPrivateLinkEndpointsResultOutput) ToGetPrivateLinkEndpointsResultOutputWithContext(ctx context.Context) GetPrivateLinkEndpointsResultOutput {
	return o
}

func (o GetPrivateLinkEndpointsResultOutput) CreateTime() pulumi.StringOutput {
	return o.ApplyT(func(v GetPrivateLinkEndpointsResult) string { return v.CreateTime }).(pulumi.StringOutput)
}

func (o GetPrivateLinkEndpointsResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v GetPrivateLinkEndpointsResult) string { return v.Description }).(pulumi.StringOutput)
}

func (o GetPrivateLinkEndpointsResultOutput) EndpointId() pulumi.StringOutput {
	return o.ApplyT(func(v GetPrivateLinkEndpointsResult) string { return v.EndpointId }).(pulumi.StringOutput)
}

func (o GetPrivateLinkEndpointsResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v GetPrivateLinkEndpointsResult) string { return v.Status }).(pulumi.StringOutput)
}

type GetPrivateLinkEndpointsResultArrayOutput struct{ *pulumi.OutputState }

func (GetPrivateLinkEndpointsResultArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetPrivateLinkEndpointsResult)(nil)).Elem()
}

func (o GetPrivateLinkEndpointsResultArrayOutput) ToGetPrivateLinkEndpointsResultArrayOutput() GetPrivateLinkEndpointsResultArrayOutput {
	return o
}

func (o GetPrivateLinkEndpointsResultArrayOutput) ToGetPrivateLinkEndpointsResultArrayOutputWithContext(ctx context.Context) GetPrivateLinkEndpointsResultArrayOutput {
	return o
}

func (o GetPrivateLinkEndpointsResultArrayOutput) Index(i pulumi.IntInput) GetPrivateLinkEndpointsResultOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetPrivateLinkEndpointsResult {
		return vs[0].([]GetPrivateLinkEndpointsResult)[vs[1].(int)]
	}).(GetPrivateLinkEndpointsResultOutput)
}

type GetPrivateLinksResult struct {
	AllowedPrincipals []string `pulumi:"allowedPrincipals"`
	DatacenterId      string   `pulumi:"datacenterId"`
	Endpoints         []string `pulumi:"endpoints"`
	ServiceName       string   `pulumi:"serviceName"`
}

// GetPrivateLinksResultInput is an input type that accepts GetPrivateLinksResultArgs and GetPrivateLinksResultOutput values.
// You can construct a concrete instance of `GetPrivateLinksResultInput` via:
//
//          GetPrivateLinksResultArgs{...}
type GetPrivateLinksResultInput interface {
	pulumi.Input

	ToGetPrivateLinksResultOutput() GetPrivateLinksResultOutput
	ToGetPrivateLinksResultOutputWithContext(context.Context) GetPrivateLinksResultOutput
}

type GetPrivateLinksResultArgs struct {
	AllowedPrincipals pulumi.StringArrayInput `pulumi:"allowedPrincipals"`
	DatacenterId      pulumi.StringInput      `pulumi:"datacenterId"`
	Endpoints         pulumi.StringArrayInput `pulumi:"endpoints"`
	ServiceName       pulumi.StringInput      `pulumi:"serviceName"`
}

func (GetPrivateLinksResultArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPrivateLinksResult)(nil)).Elem()
}

func (i GetPrivateLinksResultArgs) ToGetPrivateLinksResultOutput() GetPrivateLinksResultOutput {
	return i.ToGetPrivateLinksResultOutputWithContext(context.Background())
}

func (i GetPrivateLinksResultArgs) ToGetPrivateLinksResultOutputWithContext(ctx context.Context) GetPrivateLinksResultOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetPrivateLinksResultOutput)
}

// GetPrivateLinksResultArrayInput is an input type that accepts GetPrivateLinksResultArray and GetPrivateLinksResultArrayOutput values.
// You can construct a concrete instance of `GetPrivateLinksResultArrayInput` via:
//
//          GetPrivateLinksResultArray{ GetPrivateLinksResultArgs{...} }
type GetPrivateLinksResultArrayInput interface {
	pulumi.Input

	ToGetPrivateLinksResultArrayOutput() GetPrivateLinksResultArrayOutput
	ToGetPrivateLinksResultArrayOutputWithContext(context.Context) GetPrivateLinksResultArrayOutput
}

type GetPrivateLinksResultArray []GetPrivateLinksResultInput

func (GetPrivateLinksResultArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetPrivateLinksResult)(nil)).Elem()
}

func (i GetPrivateLinksResultArray) ToGetPrivateLinksResultArrayOutput() GetPrivateLinksResultArrayOutput {
	return i.ToGetPrivateLinksResultArrayOutputWithContext(context.Background())
}

func (i GetPrivateLinksResultArray) ToGetPrivateLinksResultArrayOutputWithContext(ctx context.Context) GetPrivateLinksResultArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetPrivateLinksResultArrayOutput)
}

type GetPrivateLinksResultOutput struct{ *pulumi.OutputState }

func (GetPrivateLinksResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPrivateLinksResult)(nil)).Elem()
}

func (o GetPrivateLinksResultOutput) ToGetPrivateLinksResultOutput() GetPrivateLinksResultOutput {
	return o
}

func (o GetPrivateLinksResultOutput) ToGetPrivateLinksResultOutputWithContext(ctx context.Context) GetPrivateLinksResultOutput {
	return o
}

func (o GetPrivateLinksResultOutput) AllowedPrincipals() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetPrivateLinksResult) []string { return v.AllowedPrincipals }).(pulumi.StringArrayOutput)
}

func (o GetPrivateLinksResultOutput) DatacenterId() pulumi.StringOutput {
	return o.ApplyT(func(v GetPrivateLinksResult) string { return v.DatacenterId }).(pulumi.StringOutput)
}

func (o GetPrivateLinksResultOutput) Endpoints() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetPrivateLinksResult) []string { return v.Endpoints }).(pulumi.StringArrayOutput)
}

func (o GetPrivateLinksResultOutput) ServiceName() pulumi.StringOutput {
	return o.ApplyT(func(v GetPrivateLinksResult) string { return v.ServiceName }).(pulumi.StringOutput)
}

type GetPrivateLinksResultArrayOutput struct{ *pulumi.OutputState }

func (GetPrivateLinksResultArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetPrivateLinksResult)(nil)).Elem()
}

func (o GetPrivateLinksResultArrayOutput) ToGetPrivateLinksResultArrayOutput() GetPrivateLinksResultArrayOutput {
	return o
}

func (o GetPrivateLinksResultArrayOutput) ToGetPrivateLinksResultArrayOutputWithContext(ctx context.Context) GetPrivateLinksResultArrayOutput {
	return o
}

func (o GetPrivateLinksResultArrayOutput) Index(i pulumi.IntInput) GetPrivateLinksResultOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetPrivateLinksResult {
		return vs[0].([]GetPrivateLinksResult)[vs[1].(int)]
	}).(GetPrivateLinksResultOutput)
}

type GetRolesResult struct {
	Description string   `pulumi:"description"`
	Effect      string   `pulumi:"effect"`
	Policies    []string `pulumi:"policies"`
	Resources   []string `pulumi:"resources"`
	RoleName    string   `pulumi:"roleName"`
}

// GetRolesResultInput is an input type that accepts GetRolesResultArgs and GetRolesResultOutput values.
// You can construct a concrete instance of `GetRolesResultInput` via:
//
//          GetRolesResultArgs{...}
type GetRolesResultInput interface {
	pulumi.Input

	ToGetRolesResultOutput() GetRolesResultOutput
	ToGetRolesResultOutputWithContext(context.Context) GetRolesResultOutput
}

type GetRolesResultArgs struct {
	Description pulumi.StringInput      `pulumi:"description"`
	Effect      pulumi.StringInput      `pulumi:"effect"`
	Policies    pulumi.StringArrayInput `pulumi:"policies"`
	Resources   pulumi.StringArrayInput `pulumi:"resources"`
	RoleName    pulumi.StringInput      `pulumi:"roleName"`
}

func (GetRolesResultArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetRolesResult)(nil)).Elem()
}

func (i GetRolesResultArgs) ToGetRolesResultOutput() GetRolesResultOutput {
	return i.ToGetRolesResultOutputWithContext(context.Background())
}

func (i GetRolesResultArgs) ToGetRolesResultOutputWithContext(ctx context.Context) GetRolesResultOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetRolesResultOutput)
}

// GetRolesResultArrayInput is an input type that accepts GetRolesResultArray and GetRolesResultArrayOutput values.
// You can construct a concrete instance of `GetRolesResultArrayInput` via:
//
//          GetRolesResultArray{ GetRolesResultArgs{...} }
type GetRolesResultArrayInput interface {
	pulumi.Input

	ToGetRolesResultArrayOutput() GetRolesResultArrayOutput
	ToGetRolesResultArrayOutputWithContext(context.Context) GetRolesResultArrayOutput
}

type GetRolesResultArray []GetRolesResultInput

func (GetRolesResultArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetRolesResult)(nil)).Elem()
}

func (i GetRolesResultArray) ToGetRolesResultArrayOutput() GetRolesResultArrayOutput {
	return i.ToGetRolesResultArrayOutputWithContext(context.Background())
}

func (i GetRolesResultArray) ToGetRolesResultArrayOutputWithContext(ctx context.Context) GetRolesResultArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetRolesResultArrayOutput)
}

type GetRolesResultOutput struct{ *pulumi.OutputState }

func (GetRolesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetRolesResult)(nil)).Elem()
}

func (o GetRolesResultOutput) ToGetRolesResultOutput() GetRolesResultOutput {
	return o
}

func (o GetRolesResultOutput) ToGetRolesResultOutputWithContext(ctx context.Context) GetRolesResultOutput {
	return o
}

func (o GetRolesResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v GetRolesResult) string { return v.Description }).(pulumi.StringOutput)
}

func (o GetRolesResultOutput) Effect() pulumi.StringOutput {
	return o.ApplyT(func(v GetRolesResult) string { return v.Effect }).(pulumi.StringOutput)
}

func (o GetRolesResultOutput) Policies() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetRolesResult) []string { return v.Policies }).(pulumi.StringArrayOutput)
}

func (o GetRolesResultOutput) Resources() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetRolesResult) []string { return v.Resources }).(pulumi.StringArrayOutput)
}

func (o GetRolesResultOutput) RoleName() pulumi.StringOutput {
	return o.ApplyT(func(v GetRolesResult) string { return v.RoleName }).(pulumi.StringOutput)
}

type GetRolesResultArrayOutput struct{ *pulumi.OutputState }

func (GetRolesResultArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetRolesResult)(nil)).Elem()
}

func (o GetRolesResultArrayOutput) ToGetRolesResultArrayOutput() GetRolesResultArrayOutput {
	return o
}

func (o GetRolesResultArrayOutput) ToGetRolesResultArrayOutputWithContext(ctx context.Context) GetRolesResultArrayOutput {
	return o
}

func (o GetRolesResultArrayOutput) Index(i pulumi.IntInput) GetRolesResultOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetRolesResult {
		return vs[0].([]GetRolesResult)[vs[1].(int)]
	}).(GetRolesResultOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*AccessListAddressInput)(nil)).Elem(), AccessListAddressArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*AccessListAddressArrayInput)(nil)).Elem(), AccessListAddressArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*AccessListAddressRequestInput)(nil)).Elem(), AccessListAddressRequestArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*AccessListAddressRequestArrayInput)(nil)).Elem(), AccessListAddressRequestArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetAccessListResultInput)(nil)).Elem(), GetAccessListResultArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetAccessListResultArrayInput)(nil)).Elem(), GetAccessListResultArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetAstraDatabasesResultInput)(nil)).Elem(), GetAstraDatabasesResultArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetAstraDatabasesResultArrayInput)(nil)).Elem(), GetAstraDatabasesResultArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetAvailableRegionsResultInput)(nil)).Elem(), GetAvailableRegionsResultArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetAvailableRegionsResultArrayInput)(nil)).Elem(), GetAvailableRegionsResultArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetKeyspacesResultInput)(nil)).Elem(), GetKeyspacesResultArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetKeyspacesResultArrayInput)(nil)).Elem(), GetKeyspacesResultArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetPrivateLinkEndpointsResultInput)(nil)).Elem(), GetPrivateLinkEndpointsResultArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetPrivateLinkEndpointsResultArrayInput)(nil)).Elem(), GetPrivateLinkEndpointsResultArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetPrivateLinksResultInput)(nil)).Elem(), GetPrivateLinksResultArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetPrivateLinksResultArrayInput)(nil)).Elem(), GetPrivateLinksResultArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetRolesResultInput)(nil)).Elem(), GetRolesResultArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetRolesResultArrayInput)(nil)).Elem(), GetRolesResultArray{})
	pulumi.RegisterOutputType(AccessListAddressOutput{})
	pulumi.RegisterOutputType(AccessListAddressArrayOutput{})
	pulumi.RegisterOutputType(AccessListAddressRequestOutput{})
	pulumi.RegisterOutputType(AccessListAddressRequestArrayOutput{})
	pulumi.RegisterOutputType(GetAccessListResultOutput{})
	pulumi.RegisterOutputType(GetAccessListResultArrayOutput{})
	pulumi.RegisterOutputType(GetAstraDatabasesResultOutput{})
	pulumi.RegisterOutputType(GetAstraDatabasesResultArrayOutput{})
	pulumi.RegisterOutputType(GetAvailableRegionsResultOutput{})
	pulumi.RegisterOutputType(GetAvailableRegionsResultArrayOutput{})
	pulumi.RegisterOutputType(GetKeyspacesResultOutput{})
	pulumi.RegisterOutputType(GetKeyspacesResultArrayOutput{})
	pulumi.RegisterOutputType(GetPrivateLinkEndpointsResultOutput{})
	pulumi.RegisterOutputType(GetPrivateLinkEndpointsResultArrayOutput{})
	pulumi.RegisterOutputType(GetPrivateLinksResultOutput{})
	pulumi.RegisterOutputType(GetPrivateLinksResultArrayOutput{})
	pulumi.RegisterOutputType(GetRolesResultOutput{})
	pulumi.RegisterOutputType(GetRolesResultArrayOutput{})
}
