// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package astra

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type AccessListAddress struct {
	Address     string  `pulumi:"address"`
	Description *string `pulumi:"description"`
	Enabled     bool    `pulumi:"enabled"`
}

// AccessListAddressInput is an input type that accepts AccessListAddressArgs and AccessListAddressOutput values.
// You can construct a concrete instance of `AccessListAddressInput` via:
//
//          AccessListAddressArgs{...}
type AccessListAddressInput interface {
	pulumi.Input

	ToAccessListAddressOutput() AccessListAddressOutput
	ToAccessListAddressOutputWithContext(context.Context) AccessListAddressOutput
}

type AccessListAddressArgs struct {
	Address     pulumi.StringInput    `pulumi:"address"`
	Description pulumi.StringPtrInput `pulumi:"description"`
	Enabled     pulumi.BoolInput      `pulumi:"enabled"`
}

func (AccessListAddressArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*AccessListAddress)(nil)).Elem()
}

func (i AccessListAddressArgs) ToAccessListAddressOutput() AccessListAddressOutput {
	return i.ToAccessListAddressOutputWithContext(context.Background())
}

func (i AccessListAddressArgs) ToAccessListAddressOutputWithContext(ctx context.Context) AccessListAddressOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AccessListAddressOutput)
}

// AccessListAddressArrayInput is an input type that accepts AccessListAddressArray and AccessListAddressArrayOutput values.
// You can construct a concrete instance of `AccessListAddressArrayInput` via:
//
//          AccessListAddressArray{ AccessListAddressArgs{...} }
type AccessListAddressArrayInput interface {
	pulumi.Input

	ToAccessListAddressArrayOutput() AccessListAddressArrayOutput
	ToAccessListAddressArrayOutputWithContext(context.Context) AccessListAddressArrayOutput
}

type AccessListAddressArray []AccessListAddressInput

func (AccessListAddressArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]AccessListAddress)(nil)).Elem()
}

func (i AccessListAddressArray) ToAccessListAddressArrayOutput() AccessListAddressArrayOutput {
	return i.ToAccessListAddressArrayOutputWithContext(context.Background())
}

func (i AccessListAddressArray) ToAccessListAddressArrayOutputWithContext(ctx context.Context) AccessListAddressArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AccessListAddressArrayOutput)
}

type AccessListAddressOutput struct{ *pulumi.OutputState }

func (AccessListAddressOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*AccessListAddress)(nil)).Elem()
}

func (o AccessListAddressOutput) ToAccessListAddressOutput() AccessListAddressOutput {
	return o
}

func (o AccessListAddressOutput) ToAccessListAddressOutputWithContext(ctx context.Context) AccessListAddressOutput {
	return o
}

func (o AccessListAddressOutput) Address() pulumi.StringOutput {
	return o.ApplyT(func(v AccessListAddress) string { return v.Address }).(pulumi.StringOutput)
}

func (o AccessListAddressOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v AccessListAddress) *string { return v.Description }).(pulumi.StringPtrOutput)
}

func (o AccessListAddressOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v AccessListAddress) bool { return v.Enabled }).(pulumi.BoolOutput)
}

type AccessListAddressArrayOutput struct{ *pulumi.OutputState }

func (AccessListAddressArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]AccessListAddress)(nil)).Elem()
}

func (o AccessListAddressArrayOutput) ToAccessListAddressArrayOutput() AccessListAddressArrayOutput {
	return o
}

func (o AccessListAddressArrayOutput) ToAccessListAddressArrayOutputWithContext(ctx context.Context) AccessListAddressArrayOutput {
	return o
}

func (o AccessListAddressArrayOutput) Index(i pulumi.IntInput) AccessListAddressOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) AccessListAddress {
		return vs[0].([]AccessListAddress)[vs[1].(int)]
	}).(AccessListAddressOutput)
}

type GetAccessListAddress struct {
	Address     string  `pulumi:"address"`
	Description *string `pulumi:"description"`
	Enabled     bool    `pulumi:"enabled"`
}

// GetAccessListAddressInput is an input type that accepts GetAccessListAddressArgs and GetAccessListAddressOutput values.
// You can construct a concrete instance of `GetAccessListAddressInput` via:
//
//          GetAccessListAddressArgs{...}
type GetAccessListAddressInput interface {
	pulumi.Input

	ToGetAccessListAddressOutput() GetAccessListAddressOutput
	ToGetAccessListAddressOutputWithContext(context.Context) GetAccessListAddressOutput
}

type GetAccessListAddressArgs struct {
	Address     pulumi.StringInput    `pulumi:"address"`
	Description pulumi.StringPtrInput `pulumi:"description"`
	Enabled     pulumi.BoolInput      `pulumi:"enabled"`
}

func (GetAccessListAddressArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetAccessListAddress)(nil)).Elem()
}

func (i GetAccessListAddressArgs) ToGetAccessListAddressOutput() GetAccessListAddressOutput {
	return i.ToGetAccessListAddressOutputWithContext(context.Background())
}

func (i GetAccessListAddressArgs) ToGetAccessListAddressOutputWithContext(ctx context.Context) GetAccessListAddressOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetAccessListAddressOutput)
}

// GetAccessListAddressArrayInput is an input type that accepts GetAccessListAddressArray and GetAccessListAddressArrayOutput values.
// You can construct a concrete instance of `GetAccessListAddressArrayInput` via:
//
//          GetAccessListAddressArray{ GetAccessListAddressArgs{...} }
type GetAccessListAddressArrayInput interface {
	pulumi.Input

	ToGetAccessListAddressArrayOutput() GetAccessListAddressArrayOutput
	ToGetAccessListAddressArrayOutputWithContext(context.Context) GetAccessListAddressArrayOutput
}

type GetAccessListAddressArray []GetAccessListAddressInput

func (GetAccessListAddressArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetAccessListAddress)(nil)).Elem()
}

func (i GetAccessListAddressArray) ToGetAccessListAddressArrayOutput() GetAccessListAddressArrayOutput {
	return i.ToGetAccessListAddressArrayOutputWithContext(context.Background())
}

func (i GetAccessListAddressArray) ToGetAccessListAddressArrayOutputWithContext(ctx context.Context) GetAccessListAddressArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetAccessListAddressArrayOutput)
}

type GetAccessListAddressOutput struct{ *pulumi.OutputState }

func (GetAccessListAddressOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetAccessListAddress)(nil)).Elem()
}

func (o GetAccessListAddressOutput) ToGetAccessListAddressOutput() GetAccessListAddressOutput {
	return o
}

func (o GetAccessListAddressOutput) ToGetAccessListAddressOutputWithContext(ctx context.Context) GetAccessListAddressOutput {
	return o
}

func (o GetAccessListAddressOutput) Address() pulumi.StringOutput {
	return o.ApplyT(func(v GetAccessListAddress) string { return v.Address }).(pulumi.StringOutput)
}

func (o GetAccessListAddressOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetAccessListAddress) *string { return v.Description }).(pulumi.StringPtrOutput)
}

func (o GetAccessListAddressOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v GetAccessListAddress) bool { return v.Enabled }).(pulumi.BoolOutput)
}

type GetAccessListAddressArrayOutput struct{ *pulumi.OutputState }

func (GetAccessListAddressArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetAccessListAddress)(nil)).Elem()
}

func (o GetAccessListAddressArrayOutput) ToGetAccessListAddressArrayOutput() GetAccessListAddressArrayOutput {
	return o
}

func (o GetAccessListAddressArrayOutput) ToGetAccessListAddressArrayOutputWithContext(ctx context.Context) GetAccessListAddressArrayOutput {
	return o
}

func (o GetAccessListAddressArrayOutput) Index(i pulumi.IntInput) GetAccessListAddressOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetAccessListAddress {
		return vs[0].([]GetAccessListAddress)[vs[1].(int)]
	}).(GetAccessListAddressOutput)
}

type GetAstraDatabasesResult struct {
	AdditionalKeyspaces []string          `pulumi:"additionalKeyspaces"`
	CloudProvider       string            `pulumi:"cloudProvider"`
	CqlshUrl            string            `pulumi:"cqlshUrl"`
	DataEndpointUrl     string            `pulumi:"dataEndpointUrl"`
	Datacenters         map[string]string `pulumi:"datacenters"`
	GrafanaUrl          string            `pulumi:"grafanaUrl"`
	GraphqlUrl          string            `pulumi:"graphqlUrl"`
	Id                  string            `pulumi:"id"`
	Keyspace            string            `pulumi:"keyspace"`
	Name                string            `pulumi:"name"`
	NodeCount           int               `pulumi:"nodeCount"`
	OrganizationId      string            `pulumi:"organizationId"`
	OwnerId             string            `pulumi:"ownerId"`
	Regions             []string          `pulumi:"regions"`
	ReplicationFactor   int               `pulumi:"replicationFactor"`
	Status              string            `pulumi:"status"`
	TotalStorage        int               `pulumi:"totalStorage"`
}

// GetAstraDatabasesResultInput is an input type that accepts GetAstraDatabasesResultArgs and GetAstraDatabasesResultOutput values.
// You can construct a concrete instance of `GetAstraDatabasesResultInput` via:
//
//          GetAstraDatabasesResultArgs{...}
type GetAstraDatabasesResultInput interface {
	pulumi.Input

	ToGetAstraDatabasesResultOutput() GetAstraDatabasesResultOutput
	ToGetAstraDatabasesResultOutputWithContext(context.Context) GetAstraDatabasesResultOutput
}

type GetAstraDatabasesResultArgs struct {
	AdditionalKeyspaces pulumi.StringArrayInput `pulumi:"additionalKeyspaces"`
	CloudProvider       pulumi.StringInput      `pulumi:"cloudProvider"`
	CqlshUrl            pulumi.StringInput      `pulumi:"cqlshUrl"`
	DataEndpointUrl     pulumi.StringInput      `pulumi:"dataEndpointUrl"`
	Datacenters         pulumi.StringMapInput   `pulumi:"datacenters"`
	GrafanaUrl          pulumi.StringInput      `pulumi:"grafanaUrl"`
	GraphqlUrl          pulumi.StringInput      `pulumi:"graphqlUrl"`
	Id                  pulumi.StringInput      `pulumi:"id"`
	Keyspace            pulumi.StringInput      `pulumi:"keyspace"`
	Name                pulumi.StringInput      `pulumi:"name"`
	NodeCount           pulumi.IntInput         `pulumi:"nodeCount"`
	OrganizationId      pulumi.StringInput      `pulumi:"organizationId"`
	OwnerId             pulumi.StringInput      `pulumi:"ownerId"`
	Regions             pulumi.StringArrayInput `pulumi:"regions"`
	ReplicationFactor   pulumi.IntInput         `pulumi:"replicationFactor"`
	Status              pulumi.StringInput      `pulumi:"status"`
	TotalStorage        pulumi.IntInput         `pulumi:"totalStorage"`
}

func (GetAstraDatabasesResultArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetAstraDatabasesResult)(nil)).Elem()
}

func (i GetAstraDatabasesResultArgs) ToGetAstraDatabasesResultOutput() GetAstraDatabasesResultOutput {
	return i.ToGetAstraDatabasesResultOutputWithContext(context.Background())
}

func (i GetAstraDatabasesResultArgs) ToGetAstraDatabasesResultOutputWithContext(ctx context.Context) GetAstraDatabasesResultOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetAstraDatabasesResultOutput)
}

// GetAstraDatabasesResultArrayInput is an input type that accepts GetAstraDatabasesResultArray and GetAstraDatabasesResultArrayOutput values.
// You can construct a concrete instance of `GetAstraDatabasesResultArrayInput` via:
//
//          GetAstraDatabasesResultArray{ GetAstraDatabasesResultArgs{...} }
type GetAstraDatabasesResultArrayInput interface {
	pulumi.Input

	ToGetAstraDatabasesResultArrayOutput() GetAstraDatabasesResultArrayOutput
	ToGetAstraDatabasesResultArrayOutputWithContext(context.Context) GetAstraDatabasesResultArrayOutput
}

type GetAstraDatabasesResultArray []GetAstraDatabasesResultInput

func (GetAstraDatabasesResultArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetAstraDatabasesResult)(nil)).Elem()
}

func (i GetAstraDatabasesResultArray) ToGetAstraDatabasesResultArrayOutput() GetAstraDatabasesResultArrayOutput {
	return i.ToGetAstraDatabasesResultArrayOutputWithContext(context.Background())
}

func (i GetAstraDatabasesResultArray) ToGetAstraDatabasesResultArrayOutputWithContext(ctx context.Context) GetAstraDatabasesResultArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetAstraDatabasesResultArrayOutput)
}

type GetAstraDatabasesResultOutput struct{ *pulumi.OutputState }

func (GetAstraDatabasesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetAstraDatabasesResult)(nil)).Elem()
}

func (o GetAstraDatabasesResultOutput) ToGetAstraDatabasesResultOutput() GetAstraDatabasesResultOutput {
	return o
}

func (o GetAstraDatabasesResultOutput) ToGetAstraDatabasesResultOutputWithContext(ctx context.Context) GetAstraDatabasesResultOutput {
	return o
}

func (o GetAstraDatabasesResultOutput) AdditionalKeyspaces() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetAstraDatabasesResult) []string { return v.AdditionalKeyspaces }).(pulumi.StringArrayOutput)
}

func (o GetAstraDatabasesResultOutput) CloudProvider() pulumi.StringOutput {
	return o.ApplyT(func(v GetAstraDatabasesResult) string { return v.CloudProvider }).(pulumi.StringOutput)
}

func (o GetAstraDatabasesResultOutput) CqlshUrl() pulumi.StringOutput {
	return o.ApplyT(func(v GetAstraDatabasesResult) string { return v.CqlshUrl }).(pulumi.StringOutput)
}

func (o GetAstraDatabasesResultOutput) DataEndpointUrl() pulumi.StringOutput {
	return o.ApplyT(func(v GetAstraDatabasesResult) string { return v.DataEndpointUrl }).(pulumi.StringOutput)
}

func (o GetAstraDatabasesResultOutput) Datacenters() pulumi.StringMapOutput {
	return o.ApplyT(func(v GetAstraDatabasesResult) map[string]string { return v.Datacenters }).(pulumi.StringMapOutput)
}

func (o GetAstraDatabasesResultOutput) GrafanaUrl() pulumi.StringOutput {
	return o.ApplyT(func(v GetAstraDatabasesResult) string { return v.GrafanaUrl }).(pulumi.StringOutput)
}

func (o GetAstraDatabasesResultOutput) GraphqlUrl() pulumi.StringOutput {
	return o.ApplyT(func(v GetAstraDatabasesResult) string { return v.GraphqlUrl }).(pulumi.StringOutput)
}

func (o GetAstraDatabasesResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetAstraDatabasesResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetAstraDatabasesResultOutput) Keyspace() pulumi.StringOutput {
	return o.ApplyT(func(v GetAstraDatabasesResult) string { return v.Keyspace }).(pulumi.StringOutput)
}

func (o GetAstraDatabasesResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetAstraDatabasesResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o GetAstraDatabasesResultOutput) NodeCount() pulumi.IntOutput {
	return o.ApplyT(func(v GetAstraDatabasesResult) int { return v.NodeCount }).(pulumi.IntOutput)
}

func (o GetAstraDatabasesResultOutput) OrganizationId() pulumi.StringOutput {
	return o.ApplyT(func(v GetAstraDatabasesResult) string { return v.OrganizationId }).(pulumi.StringOutput)
}

func (o GetAstraDatabasesResultOutput) OwnerId() pulumi.StringOutput {
	return o.ApplyT(func(v GetAstraDatabasesResult) string { return v.OwnerId }).(pulumi.StringOutput)
}

func (o GetAstraDatabasesResultOutput) Regions() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetAstraDatabasesResult) []string { return v.Regions }).(pulumi.StringArrayOutput)
}

func (o GetAstraDatabasesResultOutput) ReplicationFactor() pulumi.IntOutput {
	return o.ApplyT(func(v GetAstraDatabasesResult) int { return v.ReplicationFactor }).(pulumi.IntOutput)
}

func (o GetAstraDatabasesResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v GetAstraDatabasesResult) string { return v.Status }).(pulumi.StringOutput)
}

func (o GetAstraDatabasesResultOutput) TotalStorage() pulumi.IntOutput {
	return o.ApplyT(func(v GetAstraDatabasesResult) int { return v.TotalStorage }).(pulumi.IntOutput)
}

type GetAstraDatabasesResultArrayOutput struct{ *pulumi.OutputState }

func (GetAstraDatabasesResultArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetAstraDatabasesResult)(nil)).Elem()
}

func (o GetAstraDatabasesResultArrayOutput) ToGetAstraDatabasesResultArrayOutput() GetAstraDatabasesResultArrayOutput {
	return o
}

func (o GetAstraDatabasesResultArrayOutput) ToGetAstraDatabasesResultArrayOutputWithContext(ctx context.Context) GetAstraDatabasesResultArrayOutput {
	return o
}

func (o GetAstraDatabasesResultArrayOutput) Index(i pulumi.IntInput) GetAstraDatabasesResultOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetAstraDatabasesResult {
		return vs[0].([]GetAstraDatabasesResult)[vs[1].(int)]
	}).(GetAstraDatabasesResultOutput)
}

type GetAvailableRegionsResult struct {
	CloudProvider string `pulumi:"cloudProvider"`
	DisplayName   string `pulumi:"displayName"`
	Region        string `pulumi:"region"`
	Zone          string `pulumi:"zone"`
}

// GetAvailableRegionsResultInput is an input type that accepts GetAvailableRegionsResultArgs and GetAvailableRegionsResultOutput values.
// You can construct a concrete instance of `GetAvailableRegionsResultInput` via:
//
//          GetAvailableRegionsResultArgs{...}
type GetAvailableRegionsResultInput interface {
	pulumi.Input

	ToGetAvailableRegionsResultOutput() GetAvailableRegionsResultOutput
	ToGetAvailableRegionsResultOutputWithContext(context.Context) GetAvailableRegionsResultOutput
}

type GetAvailableRegionsResultArgs struct {
	CloudProvider pulumi.StringInput `pulumi:"cloudProvider"`
	DisplayName   pulumi.StringInput `pulumi:"displayName"`
	Region        pulumi.StringInput `pulumi:"region"`
	Zone          pulumi.StringInput `pulumi:"zone"`
}

func (GetAvailableRegionsResultArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetAvailableRegionsResult)(nil)).Elem()
}

func (i GetAvailableRegionsResultArgs) ToGetAvailableRegionsResultOutput() GetAvailableRegionsResultOutput {
	return i.ToGetAvailableRegionsResultOutputWithContext(context.Background())
}

func (i GetAvailableRegionsResultArgs) ToGetAvailableRegionsResultOutputWithContext(ctx context.Context) GetAvailableRegionsResultOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetAvailableRegionsResultOutput)
}

// GetAvailableRegionsResultArrayInput is an input type that accepts GetAvailableRegionsResultArray and GetAvailableRegionsResultArrayOutput values.
// You can construct a concrete instance of `GetAvailableRegionsResultArrayInput` via:
//
//          GetAvailableRegionsResultArray{ GetAvailableRegionsResultArgs{...} }
type GetAvailableRegionsResultArrayInput interface {
	pulumi.Input

	ToGetAvailableRegionsResultArrayOutput() GetAvailableRegionsResultArrayOutput
	ToGetAvailableRegionsResultArrayOutputWithContext(context.Context) GetAvailableRegionsResultArrayOutput
}

type GetAvailableRegionsResultArray []GetAvailableRegionsResultInput

func (GetAvailableRegionsResultArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetAvailableRegionsResult)(nil)).Elem()
}

func (i GetAvailableRegionsResultArray) ToGetAvailableRegionsResultArrayOutput() GetAvailableRegionsResultArrayOutput {
	return i.ToGetAvailableRegionsResultArrayOutputWithContext(context.Background())
}

func (i GetAvailableRegionsResultArray) ToGetAvailableRegionsResultArrayOutputWithContext(ctx context.Context) GetAvailableRegionsResultArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetAvailableRegionsResultArrayOutput)
}

type GetAvailableRegionsResultOutput struct{ *pulumi.OutputState }

func (GetAvailableRegionsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetAvailableRegionsResult)(nil)).Elem()
}

func (o GetAvailableRegionsResultOutput) ToGetAvailableRegionsResultOutput() GetAvailableRegionsResultOutput {
	return o
}

func (o GetAvailableRegionsResultOutput) ToGetAvailableRegionsResultOutputWithContext(ctx context.Context) GetAvailableRegionsResultOutput {
	return o
}

func (o GetAvailableRegionsResultOutput) CloudProvider() pulumi.StringOutput {
	return o.ApplyT(func(v GetAvailableRegionsResult) string { return v.CloudProvider }).(pulumi.StringOutput)
}

func (o GetAvailableRegionsResultOutput) DisplayName() pulumi.StringOutput {
	return o.ApplyT(func(v GetAvailableRegionsResult) string { return v.DisplayName }).(pulumi.StringOutput)
}

func (o GetAvailableRegionsResultOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v GetAvailableRegionsResult) string { return v.Region }).(pulumi.StringOutput)
}

func (o GetAvailableRegionsResultOutput) Zone() pulumi.StringOutput {
	return o.ApplyT(func(v GetAvailableRegionsResult) string { return v.Zone }).(pulumi.StringOutput)
}

type GetAvailableRegionsResultArrayOutput struct{ *pulumi.OutputState }

func (GetAvailableRegionsResultArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetAvailableRegionsResult)(nil)).Elem()
}

func (o GetAvailableRegionsResultArrayOutput) ToGetAvailableRegionsResultArrayOutput() GetAvailableRegionsResultArrayOutput {
	return o
}

func (o GetAvailableRegionsResultArrayOutput) ToGetAvailableRegionsResultArrayOutputWithContext(ctx context.Context) GetAvailableRegionsResultArrayOutput {
	return o
}

func (o GetAvailableRegionsResultArrayOutput) Index(i pulumi.IntInput) GetAvailableRegionsResultOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetAvailableRegionsResult {
		return vs[0].([]GetAvailableRegionsResult)[vs[1].(int)]
	}).(GetAvailableRegionsResultOutput)
}

type GetKeyspacesResult struct {
	Name string `pulumi:"name"`
}

// GetKeyspacesResultInput is an input type that accepts GetKeyspacesResultArgs and GetKeyspacesResultOutput values.
// You can construct a concrete instance of `GetKeyspacesResultInput` via:
//
//          GetKeyspacesResultArgs{...}
type GetKeyspacesResultInput interface {
	pulumi.Input

	ToGetKeyspacesResultOutput() GetKeyspacesResultOutput
	ToGetKeyspacesResultOutputWithContext(context.Context) GetKeyspacesResultOutput
}

type GetKeyspacesResultArgs struct {
	Name pulumi.StringInput `pulumi:"name"`
}

func (GetKeyspacesResultArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetKeyspacesResult)(nil)).Elem()
}

func (i GetKeyspacesResultArgs) ToGetKeyspacesResultOutput() GetKeyspacesResultOutput {
	return i.ToGetKeyspacesResultOutputWithContext(context.Background())
}

func (i GetKeyspacesResultArgs) ToGetKeyspacesResultOutputWithContext(ctx context.Context) GetKeyspacesResultOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetKeyspacesResultOutput)
}

// GetKeyspacesResultArrayInput is an input type that accepts GetKeyspacesResultArray and GetKeyspacesResultArrayOutput values.
// You can construct a concrete instance of `GetKeyspacesResultArrayInput` via:
//
//          GetKeyspacesResultArray{ GetKeyspacesResultArgs{...} }
type GetKeyspacesResultArrayInput interface {
	pulumi.Input

	ToGetKeyspacesResultArrayOutput() GetKeyspacesResultArrayOutput
	ToGetKeyspacesResultArrayOutputWithContext(context.Context) GetKeyspacesResultArrayOutput
}

type GetKeyspacesResultArray []GetKeyspacesResultInput

func (GetKeyspacesResultArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetKeyspacesResult)(nil)).Elem()
}

func (i GetKeyspacesResultArray) ToGetKeyspacesResultArrayOutput() GetKeyspacesResultArrayOutput {
	return i.ToGetKeyspacesResultArrayOutputWithContext(context.Background())
}

func (i GetKeyspacesResultArray) ToGetKeyspacesResultArrayOutputWithContext(ctx context.Context) GetKeyspacesResultArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetKeyspacesResultArrayOutput)
}

type GetKeyspacesResultOutput struct{ *pulumi.OutputState }

func (GetKeyspacesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetKeyspacesResult)(nil)).Elem()
}

func (o GetKeyspacesResultOutput) ToGetKeyspacesResultOutput() GetKeyspacesResultOutput {
	return o
}

func (o GetKeyspacesResultOutput) ToGetKeyspacesResultOutputWithContext(ctx context.Context) GetKeyspacesResultOutput {
	return o
}

func (o GetKeyspacesResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetKeyspacesResult) string { return v.Name }).(pulumi.StringOutput)
}

type GetKeyspacesResultArrayOutput struct{ *pulumi.OutputState }

func (GetKeyspacesResultArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetKeyspacesResult)(nil)).Elem()
}

func (o GetKeyspacesResultArrayOutput) ToGetKeyspacesResultArrayOutput() GetKeyspacesResultArrayOutput {
	return o
}

func (o GetKeyspacesResultArrayOutput) ToGetKeyspacesResultArrayOutputWithContext(ctx context.Context) GetKeyspacesResultArrayOutput {
	return o
}

func (o GetKeyspacesResultArrayOutput) Index(i pulumi.IntInput) GetKeyspacesResultOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetKeyspacesResult {
		return vs[0].([]GetKeyspacesResult)[vs[1].(int)]
	}).(GetKeyspacesResultOutput)
}

type GetPrivateLinkEndpointsResult struct {
	CreateTime  string `pulumi:"createTime"`
	Description string `pulumi:"description"`
	EndpointId  string `pulumi:"endpointId"`
	Status      string `pulumi:"status"`
}

// GetPrivateLinkEndpointsResultInput is an input type that accepts GetPrivateLinkEndpointsResultArgs and GetPrivateLinkEndpointsResultOutput values.
// You can construct a concrete instance of `GetPrivateLinkEndpointsResultInput` via:
//
//          GetPrivateLinkEndpointsResultArgs{...}
type GetPrivateLinkEndpointsResultInput interface {
	pulumi.Input

	ToGetPrivateLinkEndpointsResultOutput() GetPrivateLinkEndpointsResultOutput
	ToGetPrivateLinkEndpointsResultOutputWithContext(context.Context) GetPrivateLinkEndpointsResultOutput
}

type GetPrivateLinkEndpointsResultArgs struct {
	CreateTime  pulumi.StringInput `pulumi:"createTime"`
	Description pulumi.StringInput `pulumi:"description"`
	EndpointId  pulumi.StringInput `pulumi:"endpointId"`
	Status      pulumi.StringInput `pulumi:"status"`
}

func (GetPrivateLinkEndpointsResultArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPrivateLinkEndpointsResult)(nil)).Elem()
}

func (i GetPrivateLinkEndpointsResultArgs) ToGetPrivateLinkEndpointsResultOutput() GetPrivateLinkEndpointsResultOutput {
	return i.ToGetPrivateLinkEndpointsResultOutputWithContext(context.Background())
}

func (i GetPrivateLinkEndpointsResultArgs) ToGetPrivateLinkEndpointsResultOutputWithContext(ctx context.Context) GetPrivateLinkEndpointsResultOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetPrivateLinkEndpointsResultOutput)
}

// GetPrivateLinkEndpointsResultArrayInput is an input type that accepts GetPrivateLinkEndpointsResultArray and GetPrivateLinkEndpointsResultArrayOutput values.
// You can construct a concrete instance of `GetPrivateLinkEndpointsResultArrayInput` via:
//
//          GetPrivateLinkEndpointsResultArray{ GetPrivateLinkEndpointsResultArgs{...} }
type GetPrivateLinkEndpointsResultArrayInput interface {
	pulumi.Input

	ToGetPrivateLinkEndpointsResultArrayOutput() GetPrivateLinkEndpointsResultArrayOutput
	ToGetPrivateLinkEndpointsResultArrayOutputWithContext(context.Context) GetPrivateLinkEndpointsResultArrayOutput
}

type GetPrivateLinkEndpointsResultArray []GetPrivateLinkEndpointsResultInput

func (GetPrivateLinkEndpointsResultArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetPrivateLinkEndpointsResult)(nil)).Elem()
}

func (i GetPrivateLinkEndpointsResultArray) ToGetPrivateLinkEndpointsResultArrayOutput() GetPrivateLinkEndpointsResultArrayOutput {
	return i.ToGetPrivateLinkEndpointsResultArrayOutputWithContext(context.Background())
}

func (i GetPrivateLinkEndpointsResultArray) ToGetPrivateLinkEndpointsResultArrayOutputWithContext(ctx context.Context) GetPrivateLinkEndpointsResultArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetPrivateLinkEndpointsResultArrayOutput)
}

type GetPrivateLinkEndpointsResultOutput struct{ *pulumi.OutputState }

func (GetPrivateLinkEndpointsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPrivateLinkEndpointsResult)(nil)).Elem()
}

func (o GetPrivateLinkEndpointsResultOutput) ToGetPrivateLinkEndpointsResultOutput() GetPrivateLinkEndpointsResultOutput {
	return o
}

func (o GetPrivateLinkEndpointsResultOutput) ToGetPrivateLinkEndpointsResultOutputWithContext(ctx context.Context) GetPrivateLinkEndpointsResultOutput {
	return o
}

func (o GetPrivateLinkEndpointsResultOutput) CreateTime() pulumi.StringOutput {
	return o.ApplyT(func(v GetPrivateLinkEndpointsResult) string { return v.CreateTime }).(pulumi.StringOutput)
}

func (o GetPrivateLinkEndpointsResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v GetPrivateLinkEndpointsResult) string { return v.Description }).(pulumi.StringOutput)
}

func (o GetPrivateLinkEndpointsResultOutput) EndpointId() pulumi.StringOutput {
	return o.ApplyT(func(v GetPrivateLinkEndpointsResult) string { return v.EndpointId }).(pulumi.StringOutput)
}

func (o GetPrivateLinkEndpointsResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v GetPrivateLinkEndpointsResult) string { return v.Status }).(pulumi.StringOutput)
}

type GetPrivateLinkEndpointsResultArrayOutput struct{ *pulumi.OutputState }

func (GetPrivateLinkEndpointsResultArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetPrivateLinkEndpointsResult)(nil)).Elem()
}

func (o GetPrivateLinkEndpointsResultArrayOutput) ToGetPrivateLinkEndpointsResultArrayOutput() GetPrivateLinkEndpointsResultArrayOutput {
	return o
}

func (o GetPrivateLinkEndpointsResultArrayOutput) ToGetPrivateLinkEndpointsResultArrayOutputWithContext(ctx context.Context) GetPrivateLinkEndpointsResultArrayOutput {
	return o
}

func (o GetPrivateLinkEndpointsResultArrayOutput) Index(i pulumi.IntInput) GetPrivateLinkEndpointsResultOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetPrivateLinkEndpointsResult {
		return vs[0].([]GetPrivateLinkEndpointsResult)[vs[1].(int)]
	}).(GetPrivateLinkEndpointsResultOutput)
}

type GetPrivateLinksResult struct {
	AllowedPrincipals []string `pulumi:"allowedPrincipals"`
	DatacenterId      string   `pulumi:"datacenterId"`
	Endpoints         []string `pulumi:"endpoints"`
	ServiceName       string   `pulumi:"serviceName"`
}

// GetPrivateLinksResultInput is an input type that accepts GetPrivateLinksResultArgs and GetPrivateLinksResultOutput values.
// You can construct a concrete instance of `GetPrivateLinksResultInput` via:
//
//          GetPrivateLinksResultArgs{...}
type GetPrivateLinksResultInput interface {
	pulumi.Input

	ToGetPrivateLinksResultOutput() GetPrivateLinksResultOutput
	ToGetPrivateLinksResultOutputWithContext(context.Context) GetPrivateLinksResultOutput
}

type GetPrivateLinksResultArgs struct {
	AllowedPrincipals pulumi.StringArrayInput `pulumi:"allowedPrincipals"`
	DatacenterId      pulumi.StringInput      `pulumi:"datacenterId"`
	Endpoints         pulumi.StringArrayInput `pulumi:"endpoints"`
	ServiceName       pulumi.StringInput      `pulumi:"serviceName"`
}

func (GetPrivateLinksResultArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPrivateLinksResult)(nil)).Elem()
}

func (i GetPrivateLinksResultArgs) ToGetPrivateLinksResultOutput() GetPrivateLinksResultOutput {
	return i.ToGetPrivateLinksResultOutputWithContext(context.Background())
}

func (i GetPrivateLinksResultArgs) ToGetPrivateLinksResultOutputWithContext(ctx context.Context) GetPrivateLinksResultOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetPrivateLinksResultOutput)
}

// GetPrivateLinksResultArrayInput is an input type that accepts GetPrivateLinksResultArray and GetPrivateLinksResultArrayOutput values.
// You can construct a concrete instance of `GetPrivateLinksResultArrayInput` via:
//
//          GetPrivateLinksResultArray{ GetPrivateLinksResultArgs{...} }
type GetPrivateLinksResultArrayInput interface {
	pulumi.Input

	ToGetPrivateLinksResultArrayOutput() GetPrivateLinksResultArrayOutput
	ToGetPrivateLinksResultArrayOutputWithContext(context.Context) GetPrivateLinksResultArrayOutput
}

type GetPrivateLinksResultArray []GetPrivateLinksResultInput

func (GetPrivateLinksResultArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetPrivateLinksResult)(nil)).Elem()
}

func (i GetPrivateLinksResultArray) ToGetPrivateLinksResultArrayOutput() GetPrivateLinksResultArrayOutput {
	return i.ToGetPrivateLinksResultArrayOutputWithContext(context.Background())
}

func (i GetPrivateLinksResultArray) ToGetPrivateLinksResultArrayOutputWithContext(ctx context.Context) GetPrivateLinksResultArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetPrivateLinksResultArrayOutput)
}

type GetPrivateLinksResultOutput struct{ *pulumi.OutputState }

func (GetPrivateLinksResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPrivateLinksResult)(nil)).Elem()
}

func (o GetPrivateLinksResultOutput) ToGetPrivateLinksResultOutput() GetPrivateLinksResultOutput {
	return o
}

func (o GetPrivateLinksResultOutput) ToGetPrivateLinksResultOutputWithContext(ctx context.Context) GetPrivateLinksResultOutput {
	return o
}

func (o GetPrivateLinksResultOutput) AllowedPrincipals() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetPrivateLinksResult) []string { return v.AllowedPrincipals }).(pulumi.StringArrayOutput)
}

func (o GetPrivateLinksResultOutput) DatacenterId() pulumi.StringOutput {
	return o.ApplyT(func(v GetPrivateLinksResult) string { return v.DatacenterId }).(pulumi.StringOutput)
}

func (o GetPrivateLinksResultOutput) Endpoints() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetPrivateLinksResult) []string { return v.Endpoints }).(pulumi.StringArrayOutput)
}

func (o GetPrivateLinksResultOutput) ServiceName() pulumi.StringOutput {
	return o.ApplyT(func(v GetPrivateLinksResult) string { return v.ServiceName }).(pulumi.StringOutput)
}

type GetPrivateLinksResultArrayOutput struct{ *pulumi.OutputState }

func (GetPrivateLinksResultArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetPrivateLinksResult)(nil)).Elem()
}

func (o GetPrivateLinksResultArrayOutput) ToGetPrivateLinksResultArrayOutput() GetPrivateLinksResultArrayOutput {
	return o
}

func (o GetPrivateLinksResultArrayOutput) ToGetPrivateLinksResultArrayOutputWithContext(ctx context.Context) GetPrivateLinksResultArrayOutput {
	return o
}

func (o GetPrivateLinksResultArrayOutput) Index(i pulumi.IntInput) GetPrivateLinksResultOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetPrivateLinksResult {
		return vs[0].([]GetPrivateLinksResult)[vs[1].(int)]
	}).(GetPrivateLinksResultOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*AccessListAddressInput)(nil)).Elem(), AccessListAddressArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*AccessListAddressArrayInput)(nil)).Elem(), AccessListAddressArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetAccessListAddressInput)(nil)).Elem(), GetAccessListAddressArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetAccessListAddressArrayInput)(nil)).Elem(), GetAccessListAddressArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetAstraDatabasesResultInput)(nil)).Elem(), GetAstraDatabasesResultArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetAstraDatabasesResultArrayInput)(nil)).Elem(), GetAstraDatabasesResultArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetAvailableRegionsResultInput)(nil)).Elem(), GetAvailableRegionsResultArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetAvailableRegionsResultArrayInput)(nil)).Elem(), GetAvailableRegionsResultArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetKeyspacesResultInput)(nil)).Elem(), GetKeyspacesResultArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetKeyspacesResultArrayInput)(nil)).Elem(), GetKeyspacesResultArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetPrivateLinkEndpointsResultInput)(nil)).Elem(), GetPrivateLinkEndpointsResultArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetPrivateLinkEndpointsResultArrayInput)(nil)).Elem(), GetPrivateLinkEndpointsResultArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetPrivateLinksResultInput)(nil)).Elem(), GetPrivateLinksResultArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetPrivateLinksResultArrayInput)(nil)).Elem(), GetPrivateLinksResultArray{})
	pulumi.RegisterOutputType(AccessListAddressOutput{})
	pulumi.RegisterOutputType(AccessListAddressArrayOutput{})
	pulumi.RegisterOutputType(GetAccessListAddressOutput{})
	pulumi.RegisterOutputType(GetAccessListAddressArrayOutput{})
	pulumi.RegisterOutputType(GetAstraDatabasesResultOutput{})
	pulumi.RegisterOutputType(GetAstraDatabasesResultArrayOutput{})
	pulumi.RegisterOutputType(GetAvailableRegionsResultOutput{})
	pulumi.RegisterOutputType(GetAvailableRegionsResultArrayOutput{})
	pulumi.RegisterOutputType(GetKeyspacesResultOutput{})
	pulumi.RegisterOutputType(GetKeyspacesResultArrayOutput{})
	pulumi.RegisterOutputType(GetPrivateLinkEndpointsResultOutput{})
	pulumi.RegisterOutputType(GetPrivateLinkEndpointsResultArrayOutput{})
	pulumi.RegisterOutputType(GetPrivateLinksResultOutput{})
	pulumi.RegisterOutputType(GetPrivateLinksResultArrayOutput{})
}
