// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Astra.Outputs
{

    [OutputType]
    public sealed class GetAvailableRegionsResultResult
    {
        public readonly string CloudProvider;
        public readonly string DisplayName;
        public readonly string Region;
        public readonly string Zone;

        [OutputConstructor]
        private GetAvailableRegionsResultResult(
            string cloudProvider,

            string displayName,

            string region,

            string zone)
        {
            CloudProvider = cloudProvider;
            DisplayName = displayName;
            Region = region;
            Zone = zone;
        }
    }
}
