// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Astra.Outputs
{

    [OutputType]
    public sealed class GetRolesResultResult
    {
        public readonly string Description;
        public readonly string Effect;
        public readonly ImmutableArray<string> Policies;
        public readonly ImmutableArray<string> Resources;
        public readonly string RoleName;

        [OutputConstructor]
        private GetRolesResultResult(
            string description,

            string effect,

            ImmutableArray<string> policies,

            ImmutableArray<string> resources,

            string roleName)
        {
            Description = description;
            Effect = effect;
            Policies = policies;
            Resources = resources;
            RoleName = roleName;
        }
    }
}
