// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Astra.Outputs
{

    [OutputType]
    public sealed class GetSecureConnectBundleUrlSecureBundleCustomDomainBundleResult
    {
        public readonly string ApiFqdn;
        public readonly string CqlFqdn;
        public readonly string DashboardFqdn;
        public readonly string Domain;
        public readonly string Url;

        [OutputConstructor]
        private GetSecureConnectBundleUrlSecureBundleCustomDomainBundleResult(
            string apiFqdn,

            string cqlFqdn,

            string dashboardFqdn,

            string domain,

            string url)
        {
            ApiFqdn = apiFqdn;
            CqlFqdn = cqlFqdn;
            DashboardFqdn = dashboardFqdn;
            Domain = domain;
            Url = url;
        }
    }
}
