# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_astra.astra as __astra
    astra = __astra
    import pulumi_astra.config as __config
    config = __config
else:
    astra = _utilities.lazy_import('pulumi_astra.astra')
    config = _utilities.lazy_import('pulumi_astra.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "astra",
  "mod": "astra/accessList",
  "fqn": "pulumi_astra.astra",
  "classes": {
   "index:astra/accessList:AccessList": "AccessList"
  }
 },
 {
  "pkg": "astra",
  "mod": "astra/database",
  "fqn": "pulumi_astra.astra",
  "classes": {
   "index:astra/database:Database": "Database"
  }
 },
 {
  "pkg": "astra",
  "mod": "astra/keyspace",
  "fqn": "pulumi_astra.astra",
  "classes": {
   "index:astra/keyspace:Keyspace": "Keyspace"
  }
 },
 {
  "pkg": "astra",
  "mod": "astra/privateLink",
  "fqn": "pulumi_astra.astra",
  "classes": {
   "index:astra/privateLink:PrivateLink": "PrivateLink"
  }
 },
 {
  "pkg": "astra",
  "mod": "astra/privateLinkEndpoint",
  "fqn": "pulumi_astra.astra",
  "classes": {
   "index:astra/privateLinkEndpoint:PrivateLinkEndpoint": "PrivateLinkEndpoint"
  }
 },
 {
  "pkg": "astra",
  "mod": "astra/role",
  "fqn": "pulumi_astra.astra",
  "classes": {
   "index:astra/role:Role": "Role"
  }
 },
 {
  "pkg": "astra",
  "mod": "astra/token",
  "fqn": "pulumi_astra.astra",
  "classes": {
   "index:astra/token:Token": "Token"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "astra",
  "token": "pulumi:providers:astra",
  "fqn": "pulumi_astra",
  "class": "Provider"
 }
]
"""
)
