// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";

export namespace astra {
    export interface AccessListAddress {
        requests: pulumi.Input<pulumi.Input<inputs.astra.AccessListAddressRequest>[]>;
    }

    export interface AccessListAddressRequest {
        address: pulumi.Input<string>;
        description?: pulumi.Input<string>;
        enabled: pulumi.Input<boolean>;
    }

}
