// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * `astra.Database` provides a datasource for Astra an Astra database. This can be used to select an existing database within your Astra Organization.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as astra from "@pulumi/astra";
 *
 * const db = pulumi.output(astra.getAstraDatabase({
 *     databaseId: "8d356587-73b3-430a-9c0e-d780332e2afb",
 * }));
 * ```
 */
export function getAstraDatabase(args: GetAstraDatabaseArgs, opts?: pulumi.InvokeOptions): Promise<GetAstraDatabaseResult> {
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("astra:index/getAstraDatabase:getAstraDatabase", {
        "databaseId": args.databaseId,
    }, opts);
}

/**
 * A collection of arguments for invoking getAstraDatabase.
 */
export interface GetAstraDatabaseArgs {
    /**
     * Astra Database ID (system generated)
     */
    databaseId: string;
}

/**
 * A collection of values returned by getAstraDatabase.
 */
export interface GetAstraDatabaseResult {
    /**
     * Additional keyspaces
     */
    readonly additionalKeyspaces: string[];
    /**
     * Cloud provider (AWS, GCP, AZURE)
     */
    readonly cloudProvider: string;
    /**
     * URL for cqlsh web
     */
    readonly cqlshUrl: string;
    /**
     * REST API URL
     */
    readonly dataEndpointUrl: string;
    /**
     * Astra Database ID (system generated)
     */
    readonly databaseId: string;
    /**
     * Map of Datacenter IDs. The map key is "cloud_provider.region". Example: "GCP.us-east4".
     */
    readonly datacenters: {[key: string]: string};
    /**
     * URL for the grafana dashboard for this database
     */
    readonly grafanaUrl: string;
    /**
     * Graphql URL
     */
    readonly graphqlUrl: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * Initial keyspace
     */
    readonly keyspace: string;
    /**
     * Database name (user provided)
     */
    readonly name: string;
    /**
     * Node count (not relevant for serverless databases)
     */
    readonly nodeCount: number;
    /**
     * Ordg id (system generated)
     */
    readonly organizationId: string;
    /**
     * Owner id (system generated)
     */
    readonly ownerId: string;
    /**
     * Cloud provider region. Get list of supported regions from regions data-source
     */
    readonly regions: string[];
    /**
     * Replication Factor (not relevant for serverless databases)
     */
    readonly replicationFactor: number;
    /**
     * Database status
     */
    readonly status: string;
    /**
     * Storage Capacity (not relevant for serverelss databases)
     */
    readonly totalStorage: number;
}

export function getAstraDatabaseOutput(args: GetAstraDatabaseOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetAstraDatabaseResult> {
    return pulumi.output(args).apply(a => getAstraDatabase(a, opts))
}

/**
 * A collection of arguments for invoking getAstraDatabase.
 */
export interface GetAstraDatabaseOutputArgs {
    /**
     * Astra Database ID (system generated)
     */
    databaseId: pulumi.Input<string>;
}
