// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

/**
 * Retrieve a list of available cloud regions in Astra
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as astra from "@pulumi/astra";
 *
 * const regions = pulumi.output(astra.getAvailableRegions());
 * ```
 */
export function getAvailableRegions(opts?: pulumi.InvokeOptions): Promise<GetAvailableRegionsResult> {
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("astra:index/getAvailableRegions:getAvailableRegions", {
    }, opts);
}

/**
 * A collection of values returned by getAvailableRegions.
 */
export interface GetAvailableRegionsResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * The list of supported Astra regions by cloud provider and tier.
     */
    readonly results: outputs.GetAvailableRegionsResult[];
}
