// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * `astra.Keyspace` provides a datasource for a particular keyspace. See `astra.getKeyspaces` if you're looking to fetch all the keyspaces for a particular database.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as astra from "@pulumi/astra";
 *
 * const dev = pulumi.output(astra.getKeyspace({
 *     databaseId: "f9f4b1e0-4c05-451e-9bba-d631295a7f73",
 *     name: "puppies",
 * }));
 * ```
 */
export function getKeyspace(args: GetKeyspaceArgs, opts?: pulumi.InvokeOptions): Promise<GetKeyspaceResult> {
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("astra:index/getKeyspace:getKeyspace", {
        "databaseId": args.databaseId,
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getKeyspace.
 */
export interface GetKeyspaceArgs {
    /**
     * The ID of the Astra database.
     */
    databaseId: string;
    /**
     * The keyspace name.
     */
    name: string;
}

/**
 * A collection of values returned by getKeyspace.
 */
export interface GetKeyspaceResult {
    /**
     * The ID of the Astra database.
     */
    readonly databaseId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * The keyspace name.
     */
    readonly name: string;
}

export function getKeyspaceOutput(args: GetKeyspaceOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetKeyspaceResult> {
    return pulumi.output(args).apply(a => getKeyspace(a, opts))
}

/**
 * A collection of arguments for invoking getKeyspace.
 */
export interface GetKeyspaceOutputArgs {
    /**
     * The ID of the Astra database.
     */
    databaseId: pulumi.Input<string>;
    /**
     * The keyspace name.
     */
    name: pulumi.Input<string>;
}
