// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

/**
 * `astra.getPrivateLinks` provides a datasource that lists the private links in an Astra database.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as astra from "@pulumi/astra";
 *
 * const dev = pulumi.output(astra.getPrivateLinks({
 *     databaseId: "a6bc9c26-e7ce-424f-84c7-0a00afb12588",
 *     datacenterId: "a6bc9c26-e7ce-424f-84c7-0a00afb12588-1",
 * }));
 * ```
 */
export function getPrivateLinks(args: GetPrivateLinksArgs, opts?: pulumi.InvokeOptions): Promise<GetPrivateLinksResult> {
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("astra:index/getPrivateLinks:getPrivateLinks", {
        "databaseId": args.databaseId,
        "datacenterId": args.datacenterId,
    }, opts);
}

/**
 * A collection of arguments for invoking getPrivateLinks.
 */
export interface GetPrivateLinksArgs {
    databaseId: string;
    datacenterId: string;
}

/**
 * A collection of values returned by getPrivateLinks.
 */
export interface GetPrivateLinksResult {
    readonly databaseId: string;
    readonly datacenterId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly results: outputs.GetPrivateLinksResult[];
}

export function getPrivateLinksOutput(args: GetPrivateLinksOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetPrivateLinksResult> {
    return pulumi.output(args).apply(a => getPrivateLinks(a, opts))
}

/**
 * A collection of arguments for invoking getPrivateLinks.
 */
export interface GetPrivateLinksOutputArgs {
    databaseId: pulumi.Input<string>;
    datacenterId: pulumi.Input<string>;
}
