// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * `astra.Role` resource represents custom roles for a particular Astra Org. Custom roles can be assigned to an Astra user is to grant them granular permissions when the default roles in the UI are not specific enough. Roles are composed of policies which are granted to resources.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as astra from "@pulumiverse/astra";
 *
 * // Example role that grants policy permissions to ALL Astra DBs in an organization
 * const alldbsrole = new astra.Role("alldbsrole", {
 *     roleName: "alldbsrole",
 *     description: "Role that applies to all DBs in an org",
 *     effect: "allow",
 *     resources: [
 *         "drn:astra:org:f9f4b1e0-4c05-451e-9bba-d631295a7f73:db:*",
 *         "drn:astra:org:f9f4b1e0-4c05-451e-9bba-d631295a7f73:db:*:keyspace:*",
 *         "drn:astra:org:f9f4b1e0-4c05-451e-9bba-d631295a7f73:db:*:keyspace:*:table:*",
 *     ],
 *     policies: [
 *         "org-db-view",
 *         "db-cql",
 *         "db-table-alter",
 *         "db-table-create",
 *         "db-table-describe",
 *         "db-table-modify",
 *         "db-table-select",
 *         "db-keyspace-alter",
 *         "db-keyspace-describe",
 *         "db-keyspace-modify",
 *         "db-keyspace-authorize",
 *         "db-keyspace-drop",
 *         "db-keyspace-create",
 *         "db-keyspace-grant",
 *     ],
 * });
 * // Example resources for a more restricted role
 * // A Terraform managed Astra DB resource
 * const exampledb = new astra.Database("exampledb", {
 *     keyspace: "primaryks",
 *     cloudProvider: "gcp",
 *     regions: ["us-east1"],
 * });
 * // Example application keyspaces
 * const appks1 = new astra.Keyspace("appks1", {databaseId: exampledb.id});
 * const appks2 = new astra.Keyspace("appks2", {databaseId: exampledb.id});
 * const appks3 = new astra.Keyspace("appks3", {databaseId: exampledb.id});
 * // Example role that grants policy permissions to specific keyspaces within a single Astra DB
 * const singledbrole = new astra.Role("singledbrole", {
 *     roleName: "singledbrole",
 *     description: "Role that applies to specific keyspaces for a single Astra DB",
 *     effect: "allow",
 *     resources: [
 *         pulumi.interpolate`drn:astra:org:f9f4b1e0-4c05-451e-9bba-d631295a7f73:db:${exampledb.id}:keyspace:${exampledb.keyspace}`,
 *         pulumi.interpolate`drn:astra:org:f9f4b1e0-4c05-451e-9bba-d631295a7f73:db:${exampledb.id}:keyspace:${exampledb.keyspace}:table:*`,
 *         pulumi.interpolate`drn:astra:org:f9f4b1e0-4c05-451e-9bba-d631295a7f73:db:${exampledb.id}:keyspace:${appks1.name}`,
 *         pulumi.interpolate`drn:astra:org:f9f4b1e0-4c05-451e-9bba-d631295a7f73:db:${exampledb.id}:keyspace:${appks1.name}:table:*`,
 *         pulumi.interpolate`drn:astra:org:f9f4b1e0-4c05-451e-9bba-d631295a7f73:db:${exampledb.id}:keyspace:${appks2.name}`,
 *         pulumi.interpolate`drn:astra:org:f9f4b1e0-4c05-451e-9bba-d631295a7f73:db:${exampledb.id}:keyspace:${appks2.name}:table:*`,
 *         pulumi.interpolate`drn:astra:org:f9f4b1e0-4c05-451e-9bba-d631295a7f73:db:${exampledb.id}:keyspace:${appks3.name}`,
 *         pulumi.interpolate`drn:astra:org:f9f4b1e0-4c05-451e-9bba-d631295a7f73:db:${exampledb.id}:keyspace:${appks3.name}:table:*`,
 *         pulumi.interpolate`drn:astra:org:f9f4b1e0-4c05-451e-9bba-d631295a7f73:db:${exampledb.id}:keyspace:futureks`,
 *         pulumi.interpolate`drn:astra:org:f9f4b1e0-4c05-451e-9bba-d631295a7f73:db:${exampledb.id}:keyspace:futureks:table:*`,
 *     ],
 *     policies: [
 *         "org-db-view",
 *         "db-cql",
 *         "db-table-alter",
 *         "db-table-create",
 *         "db-table-describe",
 *         "db-table-modify",
 *         "db-table-select",
 *         "db-keyspace-alter",
 *         "db-keyspace-describe",
 *         "db-keyspace-modify",
 *         "db-keyspace-authorize",
 *         "db-keyspace-drop",
 *         "db-keyspace-create",
 *         "db-keyspace-grant",
 *     ],
 * });
 * ```
 *
 * ## Import
 *
 * ```sh
 *  $ pulumi import astra:index/role:Role example role-id
 * ```
 */
export class Role extends pulumi.CustomResource {
    /**
     * Get an existing Role resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: RoleState, opts?: pulumi.CustomResourceOptions): Role {
        return new Role(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'astra:index/role:Role';

    /**
     * Returns true if the given object is an instance of Role.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Role {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Role.__pulumiType;
    }

    /**
     * Role description
     */
    public readonly description!: pulumi.Output<string>;
    /**
     * Role effect
     */
    public readonly effect!: pulumi.Output<string>;
    /**
     * List of policies for the role. See https://docs.datastax.com/en/astra/docs/user-permissions.html#*operational*roles_detail for supported policies.
     */
    public readonly policies!: pulumi.Output<string[]>;
    /**
     * Resources for which role is applicable (format is "drn:astra:org:\n\n", followed by optional resource criteria. See example usage above).
     */
    public readonly resources!: pulumi.Output<string[]>;
    /**
     * Role ID, system generated
     */
    public /*out*/ readonly roleId!: pulumi.Output<string>;
    /**
     * Role name
     */
    public readonly roleName!: pulumi.Output<string>;

    /**
     * Create a Role resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RoleArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: RoleArgs | RoleState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as RoleState | undefined;
            resourceInputs["description"] = state ? state.description : undefined;
            resourceInputs["effect"] = state ? state.effect : undefined;
            resourceInputs["policies"] = state ? state.policies : undefined;
            resourceInputs["resources"] = state ? state.resources : undefined;
            resourceInputs["roleId"] = state ? state.roleId : undefined;
            resourceInputs["roleName"] = state ? state.roleName : undefined;
        } else {
            const args = argsOrState as RoleArgs | undefined;
            if ((!args || args.description === undefined) && !opts.urn) {
                throw new Error("Missing required property 'description'");
            }
            if ((!args || args.effect === undefined) && !opts.urn) {
                throw new Error("Missing required property 'effect'");
            }
            if ((!args || args.policies === undefined) && !opts.urn) {
                throw new Error("Missing required property 'policies'");
            }
            if ((!args || args.resources === undefined) && !opts.urn) {
                throw new Error("Missing required property 'resources'");
            }
            if ((!args || args.roleName === undefined) && !opts.urn) {
                throw new Error("Missing required property 'roleName'");
            }
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["effect"] = args ? args.effect : undefined;
            resourceInputs["policies"] = args ? args.policies : undefined;
            resourceInputs["resources"] = args ? args.resources : undefined;
            resourceInputs["roleName"] = args ? args.roleName : undefined;
            resourceInputs["roleId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Role.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Role resources.
 */
export interface RoleState {
    /**
     * Role description
     */
    description?: pulumi.Input<string>;
    /**
     * Role effect
     */
    effect?: pulumi.Input<string>;
    /**
     * List of policies for the role. See https://docs.datastax.com/en/astra/docs/user-permissions.html#*operational*roles_detail for supported policies.
     */
    policies?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Resources for which role is applicable (format is "drn:astra:org:\n\n", followed by optional resource criteria. See example usage above).
     */
    resources?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Role ID, system generated
     */
    roleId?: pulumi.Input<string>;
    /**
     * Role name
     */
    roleName?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Role resource.
 */
export interface RoleArgs {
    /**
     * Role description
     */
    description: pulumi.Input<string>;
    /**
     * Role effect
     */
    effect: pulumi.Input<string>;
    /**
     * List of policies for the role. See https://docs.datastax.com/en/astra/docs/user-permissions.html#*operational*roles_detail for supported policies.
     */
    policies: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Resources for which role is applicable (format is "drn:astra:org:\n\n", followed by optional resource criteria. See example usage above).
     */
    resources: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Role name
     */
    roleName: pulumi.Input<string>;
}
